// <auto-generated>
// Simple CRUD controller — generated so this entity is reachable/testable from Swagger + Postman.
// </auto-generated>

using TicketPortal.Api.Data;
using TicketPortal.Api.DTO;
using TicketPortal.Api.Models.People;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace TicketPortal.Api.Controllers
{
    [Authorize]
    [Route("api/[controller]")]
    [ApiController]
    public class AgentsController(AppDbContext db) : ControllerBase
    {
        [HttpGet]
        public async Task<IActionResult> GetAll()
        {
            var items = await db.Agents.ToListAsync();
            return Ok(items.Select(ToResponseDto));
        }

        [HttpGet("{id}")]
        public async Task<IActionResult> GetById(Guid id)
        {
            var item = await db.Agents.FirstOrDefaultAsync(x => x.Id == id);
            return item == null ? NotFound() : Ok(ToResponseDto(item));
        }

        [HttpPost]
        public async Task<IActionResult> Create(AgentCreateDto dto)
        {
            var item = new Agent
            {
                BusOperatorId = dto.BusOperatorId,
                Name = dto.Name,
                AgencyCode = dto.AgencyCode,
                ContactPerson = dto.ContactPerson,
                PhoneNumber = dto.PhoneNumber,
                Email = dto.Email,
                Address = dto.Address,
                CommissionPercentage = dto.CommissionPercentage,
                IsActive = dto.IsActive,
            };

            db.Agents.Add(item);
            await db.SaveChangesAsync();

            return CreatedAtAction(nameof(GetById), new { id = item.Id }, ToResponseDto(item));
        }

        [HttpPut("{id}")]
        public async Task<IActionResult> Update(Guid id, AgentUpdateDto dto)
        {
            var item = await db.Agents.FirstOrDefaultAsync(x => x.Id == id);
            if (item == null) return NotFound(new { message = "Agent not found." });

            if (dto.RowVersion == null || dto.RowVersion.Length == 0)
                return BadRequest(new { message = "RowVersion is required." });

            if (!item.RowVersion.SequenceEqual(dto.RowVersion))
            {
                return Conflict(new
                {
                    message = "This Agent was changed by another request. Please GET the latest data and try again."
                });
            }

            db.Entry(item).Property(x => x.RowVersion).OriginalValue = dto.RowVersion;

            item.BusOperatorId = dto.BusOperatorId;
            item.Name = dto.Name;
            item.AgencyCode = dto.AgencyCode;
            item.ContactPerson = dto.ContactPerson;
            item.PhoneNumber = dto.PhoneNumber;
            item.Email = dto.Email;
            item.Address = dto.Address;
            item.CommissionPercentage = dto.CommissionPercentage;
            item.IsActive = dto.IsActive;
            item.UpdatedAtUtc = DateTime.UtcNow;

            try
            {
                await db.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                return Conflict(new { message = "This Agent was already modified or deleted by another request." });
            }
            catch (DbUpdateException ex)
            {
                var error = ex.InnerException?.InnerException?.Message ?? ex.InnerException?.Message ?? ex.Message;
                return Conflict(new { message = "Could not save Agent.", details = error });
            }

            return Ok(ToResponseDto(item));
        }

        [HttpDelete("{id}")]
        public async Task<IActionResult> Delete(Guid id)
        {
            var item = await db.Agents.FirstOrDefaultAsync(x => x.Id == id);
            if (item == null) return NotFound();

            // Soft delete — real business data is never hard-deleted (see AuditableEntity.MarkDeleted).
            item.MarkDeleted();

            try
            {
                await db.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                return Conflict(new { message = "This Agent was already modified or deleted by another request." });
            }
            catch (DbUpdateException)
            {
                return Conflict(new { message = "Cannot delete this Agent — it is still referenced by other records." });
            }

            return NoContent();
        }

        private static AgentResponseDto ToResponseDto(Agent x) => new()
        {
            Id = x.Id,
            BusOperatorId = x.BusOperatorId,
            Name = x.Name,
            AgencyCode = x.AgencyCode,
            ContactPerson = x.ContactPerson,
            PhoneNumber = x.PhoneNumber,
            Email = x.Email,
            Address = x.Address,
            CommissionPercentage = x.CommissionPercentage,
            IsActive = x.IsActive,
            CreatedAtUtc = x.CreatedAtUtc,
            UpdatedAtUtc = x.UpdatedAtUtc,
            RowVersion = x.RowVersion,
        };
    }
}