// <auto-generated>
// Simple CRUD controller — generated so this entity is reachable/testable from Swagger + Postman.
// </auto-generated>

using TicketPortal.Api.Data;
using TicketPortal.Api.DTO;
using TicketPortal.Api.Models.Diagnostics;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace TicketPortal.Api.Controllers
{
    [Authorize]
    [Route("api/[controller]")]
    [ApiController]
    public class AuditLogsController(AppDbContext db) : ControllerBase
    {
        [HttpGet]
        public async Task<IActionResult> GetAll()
        {
            var items = await db.AuditLogs.ToListAsync();
            return Ok(items.Select(ToResponseDto));
        }

        [HttpGet("{id}")]
        public async Task<IActionResult> GetById(Guid id)
        {
            var item = await db.AuditLogs.FirstOrDefaultAsync(x => x.Id == id);
            return item == null ? NotFound() : Ok(ToResponseDto(item));
        }

        [HttpPost]
        public async Task<IActionResult> Create(AuditLogCreateDto dto)
        {
            var item = new AuditLog
            {
                UserId = dto.UserId,
                EntityName = dto.EntityName,
                EntityId = dto.EntityId,
                Action = dto.Action,
                OldValuesJson = dto.OldValuesJson,
                NewValuesJson = dto.NewValuesJson,
                IpAddress = dto.IpAddress,
                UserAgent = dto.UserAgent,
                CreatedAtUtc = dto.CreatedAtUtc,
            };

            db.AuditLogs.Add(item);
            await db.SaveChangesAsync();

            return CreatedAtAction(nameof(GetById), new { id = item.Id }, ToResponseDto(item));
        }

        [HttpPut("{id}")]
        public async Task<IActionResult> Update(Guid id, AuditLogUpdateDto dto)
        {
            var item = await db.AuditLogs.FirstOrDefaultAsync(x => x.Id == id);
            if (item == null) return NotFound(new { message = "AuditLog not found." });

            item.UserId = dto.UserId;
            item.EntityName = dto.EntityName;
            item.EntityId = dto.EntityId;
            item.Action = dto.Action;
            item.OldValuesJson = dto.OldValuesJson;
            item.NewValuesJson = dto.NewValuesJson;
            item.IpAddress = dto.IpAddress;
            item.UserAgent = dto.UserAgent;
            item.CreatedAtUtc = dto.CreatedAtUtc;

            try
            {
                await db.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                return Conflict(new { message = "This AuditLog was already modified or deleted by another request." });
            }
            catch (DbUpdateException ex)
            {
                var error = ex.InnerException?.InnerException?.Message ?? ex.InnerException?.Message ?? ex.Message;
                return Conflict(new { message = "Could not save AuditLog.", details = error });
            }

            return Ok(ToResponseDto(item));
        }

        [HttpDelete("{id}")]
        public async Task<IActionResult> Delete(Guid id)
        {
            var item = await db.AuditLogs.FirstOrDefaultAsync(x => x.Id == id);
            if (item == null) return NotFound();

            db.AuditLogs.Remove(item);

            try
            {
                await db.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                return Conflict(new { message = "This AuditLog was already modified or deleted by another request." });
            }
            catch (DbUpdateException)
            {
                return Conflict(new { message = "Cannot delete this AuditLog — it is still referenced by other records." });
            }

            return NoContent();
        }

        private static AuditLogResponseDto ToResponseDto(AuditLog x) => new()
        {
            Id = x.Id,
            UserId = x.UserId,
            EntityName = x.EntityName,
            EntityId = x.EntityId,
            Action = x.Action,
            OldValuesJson = x.OldValuesJson,
            NewValuesJson = x.NewValuesJson,
            IpAddress = x.IpAddress,
            UserAgent = x.UserAgent,
            CreatedAtUtc = x.CreatedAtUtc,
        };
    }
}