// <auto-generated>
// Simple CRUD controller — generated so this entity is reachable/testable from Swagger + Postman.
// </auto-generated>

using TicketPortal.Api.Data;
using TicketPortal.Api.DTO;
using TicketPortal.Api.Models.Bookings;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace TicketPortal.Api.Controllers
{
    [Authorize]
    [Route("api/[controller]")]
    [ApiController]
    public class CancellationRequestsController(AppDbContext db) : ControllerBase
    {
        [HttpGet]
        public async Task<IActionResult> GetAll()
        {
            var items = await db.CancellationRequests.ToListAsync();
            return Ok(items.Select(ToResponseDto));
        }

        [HttpGet("{id}")]
        public async Task<IActionResult> GetById(Guid id)
        {
            var item = await db.CancellationRequests.FirstOrDefaultAsync(x => x.Id == id);
            return item == null ? NotFound() : Ok(ToResponseDto(item));
        }

        [HttpPost]
        public async Task<IActionResult> Create(CancellationRequestCreateDto dto)
        {
            var item = new CancellationRequest
            {
                BookingId = dto.BookingId,
                TicketId = dto.TicketId,
                RequestedByUserId = dto.RequestedByUserId,
                ApprovedByUserId = dto.ApprovedByUserId,
                Status = dto.Status,
                Reason = dto.Reason,
                RejectedReason = dto.RejectedReason,
                RequestedRefundAmount = dto.RequestedRefundAmount,
                ApprovedRefundAmount = dto.ApprovedRefundAmount,
                RequestedAtUtc = dto.RequestedAtUtc,
                ApprovedAtUtc = dto.ApprovedAtUtc,
                CompletedAtUtc = dto.CompletedAtUtc,
            };

            db.CancellationRequests.Add(item);
            await db.SaveChangesAsync();

            return CreatedAtAction(nameof(GetById), new { id = item.Id }, ToResponseDto(item));
        }

        [HttpPut("{id}")]
        public async Task<IActionResult> Update(Guid id, CancellationRequestUpdateDto dto)
        {
            var item = await db.CancellationRequests.FirstOrDefaultAsync(x => x.Id == id);
            if (item == null) return NotFound(new { message = "CancellationRequest not found." });

            if (dto.RowVersion == null || dto.RowVersion.Length == 0)
                return BadRequest(new { message = "RowVersion is required." });

            if (!item.RowVersion.SequenceEqual(dto.RowVersion))
            {
                return Conflict(new
                {
                    message = "This CancellationRequest was changed by another request. Please GET the latest data and try again."
                });
            }

            db.Entry(item).Property(x => x.RowVersion).OriginalValue = dto.RowVersion;

            item.BookingId = dto.BookingId;
            item.TicketId = dto.TicketId;
            item.RequestedByUserId = dto.RequestedByUserId;
            item.ApprovedByUserId = dto.ApprovedByUserId;
            item.Status = dto.Status;
            item.Reason = dto.Reason;
            item.RejectedReason = dto.RejectedReason;
            item.RequestedRefundAmount = dto.RequestedRefundAmount;
            item.ApprovedRefundAmount = dto.ApprovedRefundAmount;
            item.RequestedAtUtc = dto.RequestedAtUtc;
            item.ApprovedAtUtc = dto.ApprovedAtUtc;
            item.CompletedAtUtc = dto.CompletedAtUtc;
            item.UpdatedAtUtc = DateTime.UtcNow;

            try
            {
                await db.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                return Conflict(new { message = "This CancellationRequest was already modified or deleted by another request." });
            }
            catch (DbUpdateException ex)
            {
                var error = ex.InnerException?.InnerException?.Message ?? ex.InnerException?.Message ?? ex.Message;
                return Conflict(new { message = "Could not save CancellationRequest.", details = error });
            }

            return Ok(ToResponseDto(item));
        }

        [HttpDelete("{id}")]
        public async Task<IActionResult> Delete(Guid id)
        {
            var item = await db.CancellationRequests.FirstOrDefaultAsync(x => x.Id == id);
            if (item == null) return NotFound();

            // Soft delete — real business data is never hard-deleted (see AuditableEntity.MarkDeleted).
            item.MarkDeleted();

            try
            {
                await db.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                return Conflict(new { message = "This CancellationRequest was already modified or deleted by another request." });
            }
            catch (DbUpdateException)
            {
                return Conflict(new { message = "Cannot delete this CancellationRequest — it is still referenced by other records." });
            }

            return NoContent();
        }

        private static CancellationRequestResponseDto ToResponseDto(CancellationRequest x) => new()
        {
            Id = x.Id,
            BookingId = x.BookingId,
            TicketId = x.TicketId,
            RequestedByUserId = x.RequestedByUserId,
            ApprovedByUserId = x.ApprovedByUserId,
            Status = x.Status,
            Reason = x.Reason,
            RejectedReason = x.RejectedReason,
            RequestedRefundAmount = x.RequestedRefundAmount,
            ApprovedRefundAmount = x.ApprovedRefundAmount,
            RequestedAtUtc = x.RequestedAtUtc,
            ApprovedAtUtc = x.ApprovedAtUtc,
            CompletedAtUtc = x.CompletedAtUtc,
            CreatedAtUtc = x.CreatedAtUtc,
            UpdatedAtUtc = x.UpdatedAtUtc,
            RowVersion = x.RowVersion,
        };
    }
}