// <auto-generated>
// Simple CRUD controller — generated so this entity is reachable/testable from Swagger + Postman.
// </auto-generated>

using TicketPortal.Api.Data;
using TicketPortal.Api.DTO;
using TicketPortal.Api.Models.People;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace TicketPortal.Api.Controllers
{
    [Authorize]
    [Route("api/[controller]")]
    [ApiController]
    public class CustomerWalletTransactionsController(AppDbContext db) : ControllerBase
    {
        [HttpGet]
        public async Task<IActionResult> GetAll()
        {
            var items = await db.CustomerWalletTransactions.ToListAsync();
            return Ok(items.Select(ToResponseDto));
        }

        [HttpGet("{id}")]
        public async Task<IActionResult> GetById(Guid id)
        {
            var item = await db.CustomerWalletTransactions.FirstOrDefaultAsync(x => x.Id == id);
            return item == null ? NotFound() : Ok(ToResponseDto(item));
        }

        [HttpPost]
        public async Task<IActionResult> Create(CustomerWalletTransactionCreateDto dto)
        {
            var item = new CustomerWalletTransaction
            {
                CustomerProfileId = dto.CustomerProfileId,
                BookingId = dto.BookingId,
                RefundId = dto.RefundId,
                TransactionType = dto.TransactionType,
                Amount = dto.Amount,
                BalanceAfter = dto.BalanceAfter,
                Currency = dto.Currency,
                Description = dto.Description,
            };

            db.CustomerWalletTransactions.Add(item);
            await db.SaveChangesAsync();

            return CreatedAtAction(nameof(GetById), new { id = item.Id }, ToResponseDto(item));
        }

        [HttpPut("{id}")]
        public async Task<IActionResult> Update(Guid id, CustomerWalletTransactionUpdateDto dto)
        {
            var item = await db.CustomerWalletTransactions.FirstOrDefaultAsync(x => x.Id == id);
            if (item == null) return NotFound(new { message = "CustomerWalletTransaction not found." });

            if (dto.RowVersion == null || dto.RowVersion.Length == 0)
                return BadRequest(new { message = "RowVersion is required." });

            if (!item.RowVersion.SequenceEqual(dto.RowVersion))
            {
                return Conflict(new
                {
                    message = "This CustomerWalletTransaction was changed by another request. Please GET the latest data and try again."
                });
            }

            db.Entry(item).Property(x => x.RowVersion).OriginalValue = dto.RowVersion;

            item.CustomerProfileId = dto.CustomerProfileId;
            item.BookingId = dto.BookingId;
            item.RefundId = dto.RefundId;
            item.TransactionType = dto.TransactionType;
            item.Amount = dto.Amount;
            item.BalanceAfter = dto.BalanceAfter;
            item.Currency = dto.Currency;
            item.Description = dto.Description;
            item.UpdatedAtUtc = DateTime.UtcNow;

            try
            {
                await db.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                return Conflict(new { message = "This CustomerWalletTransaction was already modified or deleted by another request." });
            }
            catch (DbUpdateException ex)
            {
                var error = ex.InnerException?.InnerException?.Message ?? ex.InnerException?.Message ?? ex.Message;
                return Conflict(new { message = "Could not save CustomerWalletTransaction.", details = error });
            }

            return Ok(ToResponseDto(item));
        }

        [HttpDelete("{id}")]
        public async Task<IActionResult> Delete(Guid id)
        {
            var item = await db.CustomerWalletTransactions.FirstOrDefaultAsync(x => x.Id == id);
            if (item == null) return NotFound();

            // Soft delete — real business data is never hard-deleted (see AuditableEntity.MarkDeleted).
            item.MarkDeleted();

            try
            {
                await db.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                return Conflict(new { message = "This CustomerWalletTransaction was already modified or deleted by another request." });
            }
            catch (DbUpdateException)
            {
                return Conflict(new { message = "Cannot delete this CustomerWalletTransaction — it is still referenced by other records." });
            }

            return NoContent();
        }

        private static CustomerWalletTransactionResponseDto ToResponseDto(CustomerWalletTransaction x) => new()
        {
            Id = x.Id,
            CustomerProfileId = x.CustomerProfileId,
            BookingId = x.BookingId,
            RefundId = x.RefundId,
            TransactionType = x.TransactionType,
            Amount = x.Amount,
            BalanceAfter = x.BalanceAfter,
            Currency = x.Currency,
            Description = x.Description,
            CreatedAtUtc = x.CreatedAtUtc,
            UpdatedAtUtc = x.UpdatedAtUtc,
            RowVersion = x.RowVersion,
        };
    }
}