// <auto-generated>
// Simple CRUD controller — generated so this entity is reachable/testable from Swagger + Postman.
// </auto-generated>

using TicketPortal.Api.Data;
using TicketPortal.Api.DTO;
using TicketPortal.Api.Models.People;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace TicketPortal.Api.Controllers
{
    [Authorize]
    [Route("api/[controller]")]
    [ApiController]
    public class DriverLicensesController(AppDbContext db) : ControllerBase
    {
        [HttpGet]
        public async Task<IActionResult> GetAll()
        {
            var items = await db.DriverLicenses.ToListAsync();
            return Ok(items.Select(ToResponseDto));
        }

        [HttpGet("{id}")]
        public async Task<IActionResult> GetById(Guid id)
        {
            var item = await db.DriverLicenses.FirstOrDefaultAsync(x => x.Id == id);
            return item == null ? NotFound() : Ok(ToResponseDto(item));
        }

        [HttpPost]
        public async Task<IActionResult> Create(DriverLicenseCreateDto dto)
        {
            var item = new DriverLicense
            {
                StaffProfileId = dto.StaffProfileId,
                LicenseNumber = dto.LicenseNumber,
                Type = dto.Type,
                IssueDate = dto.IssueDate,
                ExpiryDate = dto.ExpiryDate,
            };

            db.DriverLicenses.Add(item);
            await db.SaveChangesAsync();

            return CreatedAtAction(nameof(GetById), new { id = item.Id }, ToResponseDto(item));
        }

        [HttpPut("{id}")]
        public async Task<IActionResult> Update(Guid id, DriverLicenseUpdateDto dto)
        {
            var item = await db.DriverLicenses.FirstOrDefaultAsync(x => x.Id == id);
            if (item == null) return NotFound(new { message = "DriverLicense not found." });

            if (dto.RowVersion == null || dto.RowVersion.Length == 0)
                return BadRequest(new { message = "RowVersion is required." });

            if (!item.RowVersion.SequenceEqual(dto.RowVersion))
            {
                return Conflict(new
                {
                    message = "This DriverLicense was changed by another request. Please GET the latest data and try again."
                });
            }

            db.Entry(item).Property(x => x.RowVersion).OriginalValue = dto.RowVersion;

            item.StaffProfileId = dto.StaffProfileId;
            item.LicenseNumber = dto.LicenseNumber;
            item.Type = dto.Type;
            item.IssueDate = dto.IssueDate;
            item.ExpiryDate = dto.ExpiryDate;
            item.UpdatedAtUtc = DateTime.UtcNow;

            try
            {
                await db.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                return Conflict(new { message = "This DriverLicense was already modified or deleted by another request." });
            }
            catch (DbUpdateException ex)
            {
                var error = ex.InnerException?.InnerException?.Message ?? ex.InnerException?.Message ?? ex.Message;
                return Conflict(new { message = "Could not save DriverLicense.", details = error });
            }

            return Ok(ToResponseDto(item));
        }

        [HttpDelete("{id}")]
        public async Task<IActionResult> Delete(Guid id)
        {
            var item = await db.DriverLicenses.FirstOrDefaultAsync(x => x.Id == id);
            if (item == null) return NotFound();

            // Soft delete — real business data is never hard-deleted (see AuditableEntity.MarkDeleted).
            item.MarkDeleted();

            try
            {
                await db.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                return Conflict(new { message = "This DriverLicense was already modified or deleted by another request." });
            }
            catch (DbUpdateException)
            {
                return Conflict(new { message = "Cannot delete this DriverLicense — it is still referenced by other records." });
            }

            return NoContent();
        }

        private static DriverLicenseResponseDto ToResponseDto(DriverLicense x) => new()
        {
            Id = x.Id,
            StaffProfileId = x.StaffProfileId,
            LicenseNumber = x.LicenseNumber,
            Type = x.Type,
            IssueDate = x.IssueDate,
            ExpiryDate = x.ExpiryDate,
            CreatedAtUtc = x.CreatedAtUtc,
            UpdatedAtUtc = x.UpdatedAtUtc,
            RowVersion = x.RowVersion,
        };
    }
}