// <auto-generated>
// Simple CRUD controller — generated so this entity is reachable/testable from Swagger + Postman.
// </auto-generated>

using TicketPortal.Api.Data;
using TicketPortal.Api.DTO;
using TicketPortal.Api.Models.Payments;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace TicketPortal.Api.Controllers
{
    [Authorize]
    [Route("api/[controller]")]
    [ApiController]
    public class FareRulesController(AppDbContext db) : ControllerBase
    {
        [HttpGet]
        public async Task<IActionResult> GetAll()
        {
            var items = await db.FareRules.ToListAsync();
            return Ok(items.Select(ToResponseDto));
        }

        [HttpGet("{id}")]
        public async Task<IActionResult> GetById(Guid id)
        {
            var item = await db.FareRules.FirstOrDefaultAsync(x => x.Id == id);
            return item == null ? NotFound() : Ok(ToResponseDto(item));
        }

        [HttpPost]
        public async Task<IActionResult> Create(FareRuleCreateDto dto)
        {
            var item = new FareRule
            {
                BusOperatorId = dto.BusOperatorId,
                BusRouteId = dto.BusRouteId,
                BusType = dto.BusType,
                SeatType = dto.SeatType,
                BaseFare = dto.BaseFare,
                Currency = dto.Currency,
                EffectiveFromUtc = dto.EffectiveFromUtc,
                EffectiveToUtc = dto.EffectiveToUtc,
                IsActive = dto.IsActive,
            };

            db.FareRules.Add(item);
            await db.SaveChangesAsync();

            return CreatedAtAction(nameof(GetById), new { id = item.Id }, ToResponseDto(item));
        }

        [HttpPut("{id}")]
        public async Task<IActionResult> Update(Guid id, FareRuleUpdateDto dto)
        {
            var item = await db.FareRules.FirstOrDefaultAsync(x => x.Id == id);
            if (item == null) return NotFound(new { message = "FareRule not found." });

            if (dto.RowVersion == null || dto.RowVersion.Length == 0)
                return BadRequest(new { message = "RowVersion is required." });

            if (!item.RowVersion.SequenceEqual(dto.RowVersion))
            {
                return Conflict(new
                {
                    message = "This FareRule was changed by another request. Please GET the latest data and try again."
                });
            }

            db.Entry(item).Property(x => x.RowVersion).OriginalValue = dto.RowVersion;

            item.BusOperatorId = dto.BusOperatorId;
            item.BusRouteId = dto.BusRouteId;
            item.BusType = dto.BusType;
            item.SeatType = dto.SeatType;
            item.BaseFare = dto.BaseFare;
            item.Currency = dto.Currency;
            item.EffectiveFromUtc = dto.EffectiveFromUtc;
            item.EffectiveToUtc = dto.EffectiveToUtc;
            item.IsActive = dto.IsActive;
            item.UpdatedAtUtc = DateTime.UtcNow;

            try
            {
                await db.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                return Conflict(new { message = "This FareRule was already modified or deleted by another request." });
            }
            catch (DbUpdateException ex)
            {
                var error = ex.InnerException?.InnerException?.Message ?? ex.InnerException?.Message ?? ex.Message;
                return Conflict(new { message = "Could not save FareRule.", details = error });
            }

            return Ok(ToResponseDto(item));
        }

        [HttpDelete("{id}")]
        public async Task<IActionResult> Delete(Guid id)
        {
            var item = await db.FareRules.FirstOrDefaultAsync(x => x.Id == id);
            if (item == null) return NotFound();

            // Soft delete — real business data is never hard-deleted (see AuditableEntity.MarkDeleted).
            item.MarkDeleted();

            try
            {
                await db.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                return Conflict(new { message = "This FareRule was already modified or deleted by another request." });
            }
            catch (DbUpdateException)
            {
                return Conflict(new { message = "Cannot delete this FareRule — it is still referenced by other records." });
            }

            return NoContent();
        }

        private static FareRuleResponseDto ToResponseDto(FareRule x) => new()
        {
            Id = x.Id,
            BusOperatorId = x.BusOperatorId,
            BusRouteId = x.BusRouteId,
            BusType = x.BusType,
            SeatType = x.SeatType,
            BaseFare = x.BaseFare,
            Currency = x.Currency,
            EffectiveFromUtc = x.EffectiveFromUtc,
            EffectiveToUtc = x.EffectiveToUtc,
            IsActive = x.IsActive,
            CreatedAtUtc = x.CreatedAtUtc,
            UpdatedAtUtc = x.UpdatedAtUtc,
            RowVersion = x.RowVersion,
        };
    }
}