// <auto-generated>
// Simple CRUD controller — generated so this entity is reachable/testable from Swagger + Postman.
// </auto-generated>

using TicketPortal.Api.Data;
using TicketPortal.Api.DTO;
using TicketPortal.Api.Models.Integrations;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace TicketPortal.Api.Controllers
{
    [Authorize]
    [Route("api/[controller]")]
    [ApiController]
    public class IntegrationSyncLogsController(AppDbContext db) : ControllerBase
    {
        [HttpGet]
        public async Task<IActionResult> GetAll()
        {
            var items = await db.IntegrationSyncLogs.ToListAsync();
            return Ok(items.Select(ToResponseDto));
        }

        [HttpGet("{id}")]
        public async Task<IActionResult> GetById(Guid id)
        {
            var item = await db.IntegrationSyncLogs.FirstOrDefaultAsync(x => x.Id == id);
            return item == null ? NotFound() : Ok(ToResponseDto(item));
        }

        [HttpPost]
        public async Task<IActionResult> Create(IntegrationSyncLogCreateDto dto)
        {
            var item = new IntegrationSyncLog
            {
                OperatorIntegrationId = dto.OperatorIntegrationId,
                EntityName = dto.EntityName,
                EntityKey = dto.EntityKey,
                Operation = dto.Operation,
                Status = dto.Status,
                StartedAtUtc = dto.StartedAtUtc,
                CompletedAtUtc = dto.CompletedAtUtc,
                RequestJson = dto.RequestJson,
                ResponseJson = dto.ResponseJson,
                ErrorMessage = dto.ErrorMessage,
            };

            db.IntegrationSyncLogs.Add(item);
            await db.SaveChangesAsync();

            return CreatedAtAction(nameof(GetById), new { id = item.Id }, ToResponseDto(item));
        }

        [HttpPut("{id}")]
        public async Task<IActionResult> Update(Guid id, IntegrationSyncLogUpdateDto dto)
        {
            var item = await db.IntegrationSyncLogs.FirstOrDefaultAsync(x => x.Id == id);
            if (item == null) return NotFound(new { message = "IntegrationSyncLog not found." });

            if (dto.RowVersion == null || dto.RowVersion.Length == 0)
                return BadRequest(new { message = "RowVersion is required." });

            if (!item.RowVersion.SequenceEqual(dto.RowVersion))
            {
                return Conflict(new
                {
                    message = "This IntegrationSyncLog was changed by another request. Please GET the latest data and try again."
                });
            }

            db.Entry(item).Property(x => x.RowVersion).OriginalValue = dto.RowVersion;

            item.OperatorIntegrationId = dto.OperatorIntegrationId;
            item.EntityName = dto.EntityName;
            item.EntityKey = dto.EntityKey;
            item.Operation = dto.Operation;
            item.Status = dto.Status;
            item.StartedAtUtc = dto.StartedAtUtc;
            item.CompletedAtUtc = dto.CompletedAtUtc;
            item.RequestJson = dto.RequestJson;
            item.ResponseJson = dto.ResponseJson;
            item.ErrorMessage = dto.ErrorMessage;
            item.UpdatedAtUtc = DateTime.UtcNow;

            try
            {
                await db.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                return Conflict(new { message = "This IntegrationSyncLog was already modified or deleted by another request." });
            }
            catch (DbUpdateException ex)
            {
                var error = ex.InnerException?.InnerException?.Message ?? ex.InnerException?.Message ?? ex.Message;
                return Conflict(new { message = "Could not save IntegrationSyncLog.", details = error });
            }

            return Ok(ToResponseDto(item));
        }

        [HttpDelete("{id}")]
        public async Task<IActionResult> Delete(Guid id)
        {
            var item = await db.IntegrationSyncLogs.FirstOrDefaultAsync(x => x.Id == id);
            if (item == null) return NotFound();

            // Soft delete — real business data is never hard-deleted (see AuditableEntity.MarkDeleted).
            item.MarkDeleted();

            try
            {
                await db.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                return Conflict(new { message = "This IntegrationSyncLog was already modified or deleted by another request." });
            }
            catch (DbUpdateException)
            {
                return Conflict(new { message = "Cannot delete this IntegrationSyncLog — it is still referenced by other records." });
            }

            return NoContent();
        }

        private static IntegrationSyncLogResponseDto ToResponseDto(IntegrationSyncLog x) => new()
        {
            Id = x.Id,
            OperatorIntegrationId = x.OperatorIntegrationId,
            EntityName = x.EntityName,
            EntityKey = x.EntityKey,
            Operation = x.Operation,
            Status = x.Status,
            StartedAtUtc = x.StartedAtUtc,
            CompletedAtUtc = x.CompletedAtUtc,
            RequestJson = x.RequestJson,
            ResponseJson = x.ResponseJson,
            ErrorMessage = x.ErrorMessage,
            CreatedAtUtc = x.CreatedAtUtc,
            UpdatedAtUtc = x.UpdatedAtUtc,
            RowVersion = x.RowVersion,
        };
    }
}