// <auto-generated>
// Simple CRUD controller — generated so this entity is reachable/testable from Swagger + Postman.
// </auto-generated>

using TicketPortal.Api.Data;
using TicketPortal.Api.DTO;
using TicketPortal.Api.Models.Integrations;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace TicketPortal.Api.Controllers
{
    [Authorize]
    [Route("api/[controller]")]
    [ApiController]
    public class IntegrationWebhookLogsController(AppDbContext db) : ControllerBase
    {
        [HttpGet]
        public async Task<IActionResult> GetAll()
        {
            var items = await db.IntegrationWebhookLogs.ToListAsync();
            return Ok(items.Select(ToResponseDto));
        }

        [HttpGet("{id}")]
        public async Task<IActionResult> GetById(Guid id)
        {
            var item = await db.IntegrationWebhookLogs.FirstOrDefaultAsync(x => x.Id == id);
            return item == null ? NotFound() : Ok(ToResponseDto(item));
        }

        [HttpPost]
        public async Task<IActionResult> Create(IntegrationWebhookLogCreateDto dto)
        {
            var item = new IntegrationWebhookLog
            {
                OperatorIntegrationId = dto.OperatorIntegrationId,
                ExternalEventId = dto.ExternalEventId,
                EventType = dto.EventType,
                ReceivedAtUtc = dto.ReceivedAtUtc,
                IsProcessed = dto.IsProcessed,
                ProcessedAtUtc = dto.ProcessedAtUtc,
                PayloadJson = dto.PayloadJson,
                ErrorMessage = dto.ErrorMessage,
            };

            db.IntegrationWebhookLogs.Add(item);
            await db.SaveChangesAsync();

            return CreatedAtAction(nameof(GetById), new { id = item.Id }, ToResponseDto(item));
        }

        [HttpPut("{id}")]
        public async Task<IActionResult> Update(Guid id, IntegrationWebhookLogUpdateDto dto)
        {
            var item = await db.IntegrationWebhookLogs.FirstOrDefaultAsync(x => x.Id == id);
            if (item == null) return NotFound(new { message = "IntegrationWebhookLog not found." });

            if (dto.RowVersion == null || dto.RowVersion.Length == 0)
                return BadRequest(new { message = "RowVersion is required." });

            if (!item.RowVersion.SequenceEqual(dto.RowVersion))
            {
                return Conflict(new
                {
                    message = "This IntegrationWebhookLog was changed by another request. Please GET the latest data and try again."
                });
            }

            db.Entry(item).Property(x => x.RowVersion).OriginalValue = dto.RowVersion;

            item.OperatorIntegrationId = dto.OperatorIntegrationId;
            item.ExternalEventId = dto.ExternalEventId;
            item.EventType = dto.EventType;
            item.ReceivedAtUtc = dto.ReceivedAtUtc;
            item.IsProcessed = dto.IsProcessed;
            item.ProcessedAtUtc = dto.ProcessedAtUtc;
            item.PayloadJson = dto.PayloadJson;
            item.ErrorMessage = dto.ErrorMessage;
            item.UpdatedAtUtc = DateTime.UtcNow;

            try
            {
                await db.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                return Conflict(new { message = "This IntegrationWebhookLog was already modified or deleted by another request." });
            }
            catch (DbUpdateException ex)
            {
                var error = ex.InnerException?.InnerException?.Message ?? ex.InnerException?.Message ?? ex.Message;
                return Conflict(new { message = "Could not save IntegrationWebhookLog.", details = error });
            }

            return Ok(ToResponseDto(item));
        }

        [HttpDelete("{id}")]
        public async Task<IActionResult> Delete(Guid id)
        {
            var item = await db.IntegrationWebhookLogs.FirstOrDefaultAsync(x => x.Id == id);
            if (item == null) return NotFound();

            // Soft delete — real business data is never hard-deleted (see AuditableEntity.MarkDeleted).
            item.MarkDeleted();

            try
            {
                await db.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                return Conflict(new { message = "This IntegrationWebhookLog was already modified or deleted by another request." });
            }
            catch (DbUpdateException)
            {
                return Conflict(new { message = "Cannot delete this IntegrationWebhookLog — it is still referenced by other records." });
            }

            return NoContent();
        }

        private static IntegrationWebhookLogResponseDto ToResponseDto(IntegrationWebhookLog x) => new()
        {
            Id = x.Id,
            OperatorIntegrationId = x.OperatorIntegrationId,
            ExternalEventId = x.ExternalEventId,
            EventType = x.EventType,
            ReceivedAtUtc = x.ReceivedAtUtc,
            IsProcessed = x.IsProcessed,
            ProcessedAtUtc = x.ProcessedAtUtc,
            PayloadJson = x.PayloadJson,
            ErrorMessage = x.ErrorMessage,
            CreatedAtUtc = x.CreatedAtUtc,
            UpdatedAtUtc = x.UpdatedAtUtc,
            RowVersion = x.RowVersion,
        };
    }
}