// <auto-generated>
// Simple CRUD controller — generated so this entity is reachable/testable from Swagger + Postman.
// </auto-generated>

using TicketPortal.Api.Data;
using TicketPortal.Api.DTO;
using TicketPortal.Api.Models.Diagnostics;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace TicketPortal.Api.Controllers
{
    [Authorize]
    [Route("api/[controller]")]
    [ApiController]
    public class LoginHistoriesController(AppDbContext db) : ControllerBase
    {
        [HttpGet]
        public async Task<IActionResult> GetAll()
        {
            var items = await db.LoginHistories.ToListAsync();
            return Ok(items.Select(ToResponseDto));
        }

        [HttpGet("{id}")]
        public async Task<IActionResult> GetById(Guid id)
        {
            var item = await db.LoginHistories.FirstOrDefaultAsync(x => x.Id == id);
            return item == null ? NotFound() : Ok(ToResponseDto(item));
        }

        [HttpPost]
        public async Task<IActionResult> Create(LoginHistoryCreateDto dto)
        {
            var item = new LoginHistory
            {
                UserId = dto.UserId,
                LoginAtUtc = dto.LoginAtUtc,
                IpAddress = dto.IpAddress,
                UserAgent = dto.UserAgent,
                Success = dto.Success,
            };

            db.LoginHistories.Add(item);
            await db.SaveChangesAsync();

            return CreatedAtAction(nameof(GetById), new { id = item.Id }, ToResponseDto(item));
        }

        [HttpPut("{id}")]
        public async Task<IActionResult> Update(Guid id, LoginHistoryUpdateDto dto)
        {
            var item = await db.LoginHistories.FirstOrDefaultAsync(x => x.Id == id);
            if (item == null) return NotFound(new { message = "LoginHistory not found." });

            item.UserId = dto.UserId;
            item.LoginAtUtc = dto.LoginAtUtc;
            item.IpAddress = dto.IpAddress;
            item.UserAgent = dto.UserAgent;
            item.Success = dto.Success;

            try
            {
                await db.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                return Conflict(new { message = "This LoginHistory was already modified or deleted by another request." });
            }
            catch (DbUpdateException ex)
            {
                var error = ex.InnerException?.InnerException?.Message ?? ex.InnerException?.Message ?? ex.Message;
                return Conflict(new { message = "Could not save LoginHistory.", details = error });
            }

            return Ok(ToResponseDto(item));
        }

        [HttpDelete("{id}")]
        public async Task<IActionResult> Delete(Guid id)
        {
            var item = await db.LoginHistories.FirstOrDefaultAsync(x => x.Id == id);
            if (item == null) return NotFound();

            db.LoginHistories.Remove(item);

            try
            {
                await db.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                return Conflict(new { message = "This LoginHistory was already modified or deleted by another request." });
            }
            catch (DbUpdateException)
            {
                return Conflict(new { message = "Cannot delete this LoginHistory — it is still referenced by other records." });
            }

            return NoContent();
        }

        private static LoginHistoryResponseDto ToResponseDto(LoginHistory x) => new()
        {
            Id = x.Id,
            UserId = x.UserId,
            LoginAtUtc = x.LoginAtUtc,
            IpAddress = x.IpAddress,
            UserAgent = x.UserAgent,
            Success = x.Success,
        };
    }
}