// <auto-generated>
// Simple CRUD controller — generated so this entity is reachable/testable from Swagger + Postman.
// </auto-generated>

using TicketPortal.Api.Data;
using TicketPortal.Api.DTO;
using TicketPortal.Api.Models.Diagnostics;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace TicketPortal.Api.Controllers
{
    [Authorize]
    [Route("api/[controller]")]
    [ApiController]
    public class NotificationLogsController(AppDbContext db) : ControllerBase
    {
        [HttpGet]
        public async Task<IActionResult> GetAll()
        {
            var items = await db.NotificationLogs.ToListAsync();
            return Ok(items.Select(ToResponseDto));
        }

        [HttpGet("{id}")]
        public async Task<IActionResult> GetById(Guid id)
        {
            var item = await db.NotificationLogs.FirstOrDefaultAsync(x => x.Id == id);
            return item == null ? NotFound() : Ok(ToResponseDto(item));
        }

        [HttpPost]
        public async Task<IActionResult> Create(NotificationLogCreateDto dto)
        {
            var item = new NotificationLog
            {
                BookingId = dto.BookingId,
                TicketId = dto.TicketId,
                UserId = dto.UserId,
                Channel = dto.Channel,
                Recipient = dto.Recipient,
                Subject = dto.Subject,
                Message = dto.Message,
                Status = dto.Status,
                ProviderMessageId = dto.ProviderMessageId,
                ErrorMessage = dto.ErrorMessage,
                SentAtUtc = dto.SentAtUtc,
            };

            db.NotificationLogs.Add(item);
            await db.SaveChangesAsync();

            return CreatedAtAction(nameof(GetById), new { id = item.Id }, ToResponseDto(item));
        }

        [HttpPut("{id}")]
        public async Task<IActionResult> Update(Guid id, NotificationLogUpdateDto dto)
        {
            var item = await db.NotificationLogs.FirstOrDefaultAsync(x => x.Id == id);
            if (item == null) return NotFound(new { message = "NotificationLog not found." });

            if (dto.RowVersion == null || dto.RowVersion.Length == 0)
                return BadRequest(new { message = "RowVersion is required." });

            if (!item.RowVersion.SequenceEqual(dto.RowVersion))
            {
                return Conflict(new
                {
                    message = "This NotificationLog was changed by another request. Please GET the latest data and try again."
                });
            }

            db.Entry(item).Property(x => x.RowVersion).OriginalValue = dto.RowVersion;

            item.BookingId = dto.BookingId;
            item.TicketId = dto.TicketId;
            item.UserId = dto.UserId;
            item.Channel = dto.Channel;
            item.Recipient = dto.Recipient;
            item.Subject = dto.Subject;
            item.Message = dto.Message;
            item.Status = dto.Status;
            item.ProviderMessageId = dto.ProviderMessageId;
            item.ErrorMessage = dto.ErrorMessage;
            item.SentAtUtc = dto.SentAtUtc;
            item.UpdatedAtUtc = DateTime.UtcNow;

            try
            {
                await db.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                return Conflict(new { message = "This NotificationLog was already modified or deleted by another request." });
            }
            catch (DbUpdateException ex)
            {
                var error = ex.InnerException?.InnerException?.Message ?? ex.InnerException?.Message ?? ex.Message;
                return Conflict(new { message = "Could not save NotificationLog.", details = error });
            }

            return Ok(ToResponseDto(item));
        }

        [HttpDelete("{id}")]
        public async Task<IActionResult> Delete(Guid id)
        {
            var item = await db.NotificationLogs.FirstOrDefaultAsync(x => x.Id == id);
            if (item == null) return NotFound();

            // Soft delete — real business data is never hard-deleted (see AuditableEntity.MarkDeleted).
            item.MarkDeleted();

            try
            {
                await db.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                return Conflict(new { message = "This NotificationLog was already modified or deleted by another request." });
            }
            catch (DbUpdateException)
            {
                return Conflict(new { message = "Cannot delete this NotificationLog — it is still referenced by other records." });
            }

            return NoContent();
        }

        private static NotificationLogResponseDto ToResponseDto(NotificationLog x) => new()
        {
            Id = x.Id,
            BookingId = x.BookingId,
            TicketId = x.TicketId,
            UserId = x.UserId,
            Channel = x.Channel,
            Recipient = x.Recipient,
            Subject = x.Subject,
            Message = x.Message,
            Status = x.Status,
            ProviderMessageId = x.ProviderMessageId,
            ErrorMessage = x.ErrorMessage,
            SentAtUtc = x.SentAtUtc,
            CreatedAtUtc = x.CreatedAtUtc,
            UpdatedAtUtc = x.UpdatedAtUtc,
            RowVersion = x.RowVersion,
        };
    }
}