// <auto-generated>
// Simple CRUD controller — generated so this entity is reachable/testable from Swagger + Postman.
// </auto-generated>

using TicketPortal.Api.Data;
using TicketPortal.Api.DTO;
using TicketPortal.Api.Models.Finance;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace TicketPortal.Api.Controllers
{
    [Authorize]
    [Route("api/[controller]")]
    [ApiController]
    public class OperatorSettlementsController(AppDbContext db) : ControllerBase
    {
        [HttpGet]
        public async Task<IActionResult> GetAll()
        {
            var items = await db.OperatorSettlements.ToListAsync();
            return Ok(items.Select(ToResponseDto));
        }

        [HttpGet("{id}")]
        public async Task<IActionResult> GetById(Guid id)
        {
            var item = await db.OperatorSettlements.FirstOrDefaultAsync(x => x.Id == id);
            return item == null ? NotFound() : Ok(ToResponseDto(item));
        }

        [HttpPost]
        public async Task<IActionResult> Create(OperatorSettlementCreateDto dto)
        {
            var item = new OperatorSettlement
            {
                BusOperatorId = dto.BusOperatorId,
                OperatorStatementId = dto.OperatorStatementId,
                OperatorInvoiceId = dto.OperatorInvoiceId,
                SettlementNo = dto.SettlementNo,
                FromDate = dto.FromDate,
                ToDate = dto.ToDate,
                Direction = dto.Direction,
                Status = dto.Status,
                OnlineGrossAmount = dto.OnlineGrossAmount,
                OfflineGrossAmount = dto.OfflineGrossAmount,
                PlatformCharge = dto.PlatformCharge,
                GatewayCharge = dto.GatewayCharge,
                RefundAmount = dto.RefundAmount,
                NetAmount = dto.NetAmount,
                PaidAtUtc = dto.PaidAtUtc,
                Remarks = dto.Remarks,
            };

            db.OperatorSettlements.Add(item);
            await db.SaveChangesAsync();

            return CreatedAtAction(nameof(GetById), new { id = item.Id }, ToResponseDto(item));
        }

        [HttpPut("{id}")]
        public async Task<IActionResult> Update(Guid id, OperatorSettlementUpdateDto dto)
        {
            var item = await db.OperatorSettlements.FirstOrDefaultAsync(x => x.Id == id);
            if (item == null) return NotFound(new { message = "OperatorSettlement not found." });

            if (dto.RowVersion == null || dto.RowVersion.Length == 0)
                return BadRequest(new { message = "RowVersion is required." });

            if (!item.RowVersion.SequenceEqual(dto.RowVersion))
            {
                return Conflict(new
                {
                    message = "This OperatorSettlement was changed by another request. Please GET the latest data and try again."
                });
            }

            db.Entry(item).Property(x => x.RowVersion).OriginalValue = dto.RowVersion;

            item.BusOperatorId = dto.BusOperatorId;
            item.OperatorStatementId = dto.OperatorStatementId;
            item.OperatorInvoiceId = dto.OperatorInvoiceId;
            item.SettlementNo = dto.SettlementNo;
            item.FromDate = dto.FromDate;
            item.ToDate = dto.ToDate;
            item.Direction = dto.Direction;
            item.Status = dto.Status;
            item.OnlineGrossAmount = dto.OnlineGrossAmount;
            item.OfflineGrossAmount = dto.OfflineGrossAmount;
            item.PlatformCharge = dto.PlatformCharge;
            item.GatewayCharge = dto.GatewayCharge;
            item.RefundAmount = dto.RefundAmount;
            item.NetAmount = dto.NetAmount;
            item.PaidAtUtc = dto.PaidAtUtc;
            item.Remarks = dto.Remarks;
            item.UpdatedAtUtc = DateTime.UtcNow;

            try
            {
                await db.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                return Conflict(new { message = "This OperatorSettlement was already modified or deleted by another request." });
            }
            catch (DbUpdateException ex)
            {
                var error = ex.InnerException?.InnerException?.Message ?? ex.InnerException?.Message ?? ex.Message;
                return Conflict(new { message = "Could not save OperatorSettlement.", details = error });
            }

            return Ok(ToResponseDto(item));
        }

        [HttpDelete("{id}")]
        public async Task<IActionResult> Delete(Guid id)
        {
            var item = await db.OperatorSettlements.FirstOrDefaultAsync(x => x.Id == id);
            if (item == null) return NotFound();

            // Soft delete — real business data is never hard-deleted (see AuditableEntity.MarkDeleted).
            item.MarkDeleted();

            try
            {
                await db.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                return Conflict(new { message = "This OperatorSettlement was already modified or deleted by another request." });
            }
            catch (DbUpdateException)
            {
                return Conflict(new { message = "Cannot delete this OperatorSettlement — it is still referenced by other records." });
            }

            return NoContent();
        }

        private static OperatorSettlementResponseDto ToResponseDto(OperatorSettlement x) => new()
        {
            Id = x.Id,
            BusOperatorId = x.BusOperatorId,
            OperatorStatementId = x.OperatorStatementId,
            OperatorInvoiceId = x.OperatorInvoiceId,
            SettlementNo = x.SettlementNo,
            FromDate = x.FromDate,
            ToDate = x.ToDate,
            Direction = x.Direction,
            Status = x.Status,
            OnlineGrossAmount = x.OnlineGrossAmount,
            OfflineGrossAmount = x.OfflineGrossAmount,
            PlatformCharge = x.PlatformCharge,
            GatewayCharge = x.GatewayCharge,
            RefundAmount = x.RefundAmount,
            NetAmount = x.NetAmount,
            PaidAtUtc = x.PaidAtUtc,
            Remarks = x.Remarks,
            CreatedAtUtc = x.CreatedAtUtc,
            UpdatedAtUtc = x.UpdatedAtUtc,
            RowVersion = x.RowVersion,
        };
    }
}