// <auto-generated>
// Simple CRUD controller — generated so this entity is reachable/testable from Swagger + Postman.
// </auto-generated>

using TicketPortal.Api.Data;
using TicketPortal.Api.DTO;
using TicketPortal.Api.Models.Integrations;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace TicketPortal.Api.Controllers
{
    [Authorize]
    [Route("api/[controller]")]
    [ApiController]
    public class OperatorIntegrationsController(AppDbContext db) : ControllerBase
    {
        [HttpGet]
        public async Task<IActionResult> GetAll()
        {
            var items = await db.OperatorIntegrations.ToListAsync();
            return Ok(items.Select(ToResponseDto));
        }

        [HttpGet("{id}")]
        public async Task<IActionResult> GetById(Guid id)
        {
            var item = await db.OperatorIntegrations.FirstOrDefaultAsync(x => x.Id == id);
            return item == null ? NotFound() : Ok(ToResponseDto(item));
        }

        [HttpPost]
        public async Task<IActionResult> Create(OperatorIntegrationCreateDto dto)
        {
            var item = new OperatorIntegration
            {
                BusOperatorId = dto.BusOperatorId,
                Name = dto.Name,
                BaseUrl = dto.BaseUrl,
                AuthType = dto.AuthType,
                ApiKeyHeaderName = dto.ApiKeyHeaderName,
                SecretReference = dto.SecretReference,
                TimeoutSeconds = dto.TimeoutSeconds,
                IsActive = dto.IsActive,
                LastSuccessfulSyncAtUtc = dto.LastSuccessfulSyncAtUtc,
            };

            db.OperatorIntegrations.Add(item);
            await db.SaveChangesAsync();

            return CreatedAtAction(nameof(GetById), new { id = item.Id }, ToResponseDto(item));
        }

        [HttpPut("{id}")]
        public async Task<IActionResult> Update(Guid id, OperatorIntegrationUpdateDto dto)
        {
            var item = await db.OperatorIntegrations.FirstOrDefaultAsync(x => x.Id == id);
            if (item == null) return NotFound(new { message = "OperatorIntegration not found." });

            if (dto.RowVersion == null || dto.RowVersion.Length == 0)
                return BadRequest(new { message = "RowVersion is required." });

            if (!item.RowVersion.SequenceEqual(dto.RowVersion))
            {
                return Conflict(new
                {
                    message = "This OperatorIntegration was changed by another request. Please GET the latest data and try again."
                });
            }

            db.Entry(item).Property(x => x.RowVersion).OriginalValue = dto.RowVersion;

            item.BusOperatorId = dto.BusOperatorId;
            item.Name = dto.Name;
            item.BaseUrl = dto.BaseUrl;
            item.AuthType = dto.AuthType;
            item.ApiKeyHeaderName = dto.ApiKeyHeaderName;
            item.SecretReference = dto.SecretReference;
            item.TimeoutSeconds = dto.TimeoutSeconds;
            item.IsActive = dto.IsActive;
            item.LastSuccessfulSyncAtUtc = dto.LastSuccessfulSyncAtUtc;
            item.UpdatedAtUtc = DateTime.UtcNow;

            try
            {
                await db.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                return Conflict(new { message = "This OperatorIntegration was already modified or deleted by another request." });
            }
            catch (DbUpdateException ex)
            {
                var error = ex.InnerException?.InnerException?.Message ?? ex.InnerException?.Message ?? ex.Message;
                return Conflict(new { message = "Could not save OperatorIntegration.", details = error });
            }

            return Ok(ToResponseDto(item));
        }

        [HttpDelete("{id}")]
        public async Task<IActionResult> Delete(Guid id)
        {
            var item = await db.OperatorIntegrations.FirstOrDefaultAsync(x => x.Id == id);
            if (item == null) return NotFound();

            // Soft delete — real business data is never hard-deleted (see AuditableEntity.MarkDeleted).
            item.MarkDeleted();

            try
            {
                await db.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                return Conflict(new { message = "This OperatorIntegration was already modified or deleted by another request." });
            }
            catch (DbUpdateException)
            {
                return Conflict(new { message = "Cannot delete this OperatorIntegration — it is still referenced by other records." });
            }

            return NoContent();
        }

        private static OperatorIntegrationResponseDto ToResponseDto(OperatorIntegration x) => new()
        {
            Id = x.Id,
            BusOperatorId = x.BusOperatorId,
            Name = x.Name,
            BaseUrl = x.BaseUrl,
            AuthType = x.AuthType,
            ApiKeyHeaderName = x.ApiKeyHeaderName,
            SecretReference = x.SecretReference,
            TimeoutSeconds = x.TimeoutSeconds,
            IsActive = x.IsActive,
            LastSuccessfulSyncAtUtc = x.LastSuccessfulSyncAtUtc,
            CreatedAtUtc = x.CreatedAtUtc,
            UpdatedAtUtc = x.UpdatedAtUtc,
            RowVersion = x.RowVersion,
        };
    }
}