// <auto-generated>
// Simple CRUD controller — generated so this entity is reachable/testable from Swagger + Postman.
// </auto-generated>

using TicketPortal.Api.Data;
using TicketPortal.Api.DTO;
using TicketPortal.Api.Models.Finance;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace TicketPortal.Api.Controllers
{
    [Authorize]
    [Route("api/[controller]")]
    [ApiController]
    public class OperatorWalletsController(AppDbContext db) : ControllerBase
    {
        [HttpGet]
        public async Task<IActionResult> GetAll()
        {
            var items = await db.OperatorWallets.ToListAsync();
            return Ok(items.Select(ToResponseDto));
        }

        [HttpGet("{id}")]
        public async Task<IActionResult> GetById(Guid id)
        {
            var item = await db.OperatorWallets.FirstOrDefaultAsync(x => x.Id == id);
            return item == null ? NotFound() : Ok(ToResponseDto(item));
        }

        [HttpPost]
        public async Task<IActionResult> Create(OperatorWalletCreateDto dto)
        {
            var item = new OperatorWallet
            {
                BusOperatorId = dto.BusOperatorId,
                TotalOnlineSalesAmount = dto.TotalOnlineSalesAmount,
                TotalCounterSalesAmount = dto.TotalCounterSalesAmount,
                PendingSettlementBalance = dto.PendingSettlementBalance,
                AvailablePayoutBalance = dto.AvailablePayoutBalance,
                WithdrawnAmount = dto.WithdrawnAmount,
                TotalPlatformCommission = dto.TotalPlatformCommission,
                TotalGatewayCharge = dto.TotalGatewayCharge,
                OperatorReceivableFromPlatform = dto.OperatorReceivableFromPlatform,
                PlatformReceivableFromOperator = dto.PlatformReceivableFromOperator,
                LastStatementDateUtc = dto.LastStatementDateUtc,
                LastSettlementDateUtc = dto.LastSettlementDateUtc,
                IsActive = dto.IsActive,
            };

            db.OperatorWallets.Add(item);
            await db.SaveChangesAsync();

            return CreatedAtAction(nameof(GetById), new { id = item.Id }, ToResponseDto(item));
        }

        [HttpPut("{id}")]
        public async Task<IActionResult> Update(Guid id, OperatorWalletUpdateDto dto)
        {
            var item = await db.OperatorWallets.FirstOrDefaultAsync(x => x.Id == id);
            if (item == null) return NotFound(new { message = "OperatorWallet not found." });

            if (dto.RowVersion == null || dto.RowVersion.Length == 0)
                return BadRequest(new { message = "RowVersion is required." });

            if (!item.RowVersion.SequenceEqual(dto.RowVersion))
            {
                return Conflict(new
                {
                    message = "This OperatorWallet was changed by another request. Please GET the latest data and try again."
                });
            }

            db.Entry(item).Property(x => x.RowVersion).OriginalValue = dto.RowVersion;

            item.BusOperatorId = dto.BusOperatorId;
            item.TotalOnlineSalesAmount = dto.TotalOnlineSalesAmount;
            item.TotalCounterSalesAmount = dto.TotalCounterSalesAmount;
            item.PendingSettlementBalance = dto.PendingSettlementBalance;
            item.AvailablePayoutBalance = dto.AvailablePayoutBalance;
            item.WithdrawnAmount = dto.WithdrawnAmount;
            item.TotalPlatformCommission = dto.TotalPlatformCommission;
            item.TotalGatewayCharge = dto.TotalGatewayCharge;
            item.OperatorReceivableFromPlatform = dto.OperatorReceivableFromPlatform;
            item.PlatformReceivableFromOperator = dto.PlatformReceivableFromOperator;
            item.LastStatementDateUtc = dto.LastStatementDateUtc;
            item.LastSettlementDateUtc = dto.LastSettlementDateUtc;
            item.IsActive = dto.IsActive;
            item.UpdatedAtUtc = DateTime.UtcNow;

            try
            {
                await db.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                return Conflict(new { message = "This OperatorWallet was already modified or deleted by another request." });
            }
            catch (DbUpdateException ex)
            {
                var error = ex.InnerException?.InnerException?.Message ?? ex.InnerException?.Message ?? ex.Message;
                return Conflict(new { message = "Could not save OperatorWallet.", details = error });
            }

            return Ok(ToResponseDto(item));
        }

        [HttpDelete("{id}")]
        public async Task<IActionResult> Delete(Guid id)
        {
            var item = await db.OperatorWallets.FirstOrDefaultAsync(x => x.Id == id);
            if (item == null) return NotFound();

            // Soft delete — real business data is never hard-deleted (see AuditableEntity.MarkDeleted).
            item.MarkDeleted();

            try
            {
                await db.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                return Conflict(new { message = "This OperatorWallet was already modified or deleted by another request." });
            }
            catch (DbUpdateException)
            {
                return Conflict(new { message = "Cannot delete this OperatorWallet — it is still referenced by other records." });
            }

            return NoContent();
        }

        private static OperatorWalletResponseDto ToResponseDto(OperatorWallet x) => new()
        {
            Id = x.Id,
            BusOperatorId = x.BusOperatorId,
            TotalOnlineSalesAmount = x.TotalOnlineSalesAmount,
            TotalCounterSalesAmount = x.TotalCounterSalesAmount,
            PendingSettlementBalance = x.PendingSettlementBalance,
            AvailablePayoutBalance = x.AvailablePayoutBalance,
            WithdrawnAmount = x.WithdrawnAmount,
            TotalPlatformCommission = x.TotalPlatformCommission,
            TotalGatewayCharge = x.TotalGatewayCharge,
            OperatorReceivableFromPlatform = x.OperatorReceivableFromPlatform,
            PlatformReceivableFromOperator = x.PlatformReceivableFromOperator,
            LastStatementDateUtc = x.LastStatementDateUtc,
            LastSettlementDateUtc = x.LastSettlementDateUtc,
            IsActive = x.IsActive,
            CreatedAtUtc = x.CreatedAtUtc,
            UpdatedAtUtc = x.UpdatedAtUtc,
            RowVersion = x.RowVersion,
        };
    }
}