// <auto-generated>
// Simple CRUD controller — generated so this entity is reachable/testable from Swagger + Postman.
// </auto-generated>

using TicketPortal.Api.Data;
using TicketPortal.Api.DTO;
using TicketPortal.Api.Models.Finance;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace TicketPortal.Api.Controllers
{
    [Authorize]
    [Route("api/[controller]")]
    [ApiController]
    public class OperatorStatementsController(AppDbContext db) : ControllerBase
    {
        [HttpGet]
        public async Task<IActionResult> GetAll()
        {
            var items = await db.OperatorStatements.ToListAsync();
            return Ok(items.Select(ToResponseDto));
        }

        [HttpGet("{id}")]
        public async Task<IActionResult> GetById(Guid id)
        {
            var item = await db.OperatorStatements.FirstOrDefaultAsync(x => x.Id == id);
            return item == null ? NotFound() : Ok(ToResponseDto(item));
        }

        [HttpPost]
        public async Task<IActionResult> Create(OperatorStatementCreateDto dto)
        {
            var item = new OperatorStatement
            {
                BusOperatorId = dto.BusOperatorId,
                StatementNo = dto.StatementNo,
                FromDate = dto.FromDate,
                ToDate = dto.ToDate,
                PlatformPayableToOperator = dto.PlatformPayableToOperator,
                OperatorPayableToPlatform = dto.OperatorPayableToPlatform,
                NetAmount = dto.NetAmount,
                NetDirection = dto.NetDirection,
                Status = dto.Status,
            };

            db.OperatorStatements.Add(item);
            await db.SaveChangesAsync();

            return CreatedAtAction(nameof(GetById), new { id = item.Id }, ToResponseDto(item));
        }

        [HttpPut("{id}")]
        public async Task<IActionResult> Update(Guid id, OperatorStatementUpdateDto dto)
        {
            var item = await db.OperatorStatements.FirstOrDefaultAsync(x => x.Id == id);
            if (item == null) return NotFound(new { message = "OperatorStatement not found." });

            if (dto.RowVersion == null || dto.RowVersion.Length == 0)
                return BadRequest(new { message = "RowVersion is required." });

            if (!item.RowVersion.SequenceEqual(dto.RowVersion))
            {
                return Conflict(new
                {
                    message = "This OperatorStatement was changed by another request. Please GET the latest data and try again."
                });
            }

            db.Entry(item).Property(x => x.RowVersion).OriginalValue = dto.RowVersion;

            item.BusOperatorId = dto.BusOperatorId;
            item.StatementNo = dto.StatementNo;
            item.FromDate = dto.FromDate;
            item.ToDate = dto.ToDate;
            item.PlatformPayableToOperator = dto.PlatformPayableToOperator;
            item.OperatorPayableToPlatform = dto.OperatorPayableToPlatform;
            item.NetAmount = dto.NetAmount;
            item.NetDirection = dto.NetDirection;
            item.Status = dto.Status;
            item.UpdatedAtUtc = DateTime.UtcNow;

            try
            {
                await db.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                return Conflict(new { message = "This OperatorStatement was already modified or deleted by another request." });
            }
            catch (DbUpdateException ex)
            {
                var error = ex.InnerException?.InnerException?.Message ?? ex.InnerException?.Message ?? ex.Message;
                return Conflict(new { message = "Could not save OperatorStatement.", details = error });
            }

            return Ok(ToResponseDto(item));
        }

        [HttpDelete("{id}")]
        public async Task<IActionResult> Delete(Guid id)
        {
            var item = await db.OperatorStatements.FirstOrDefaultAsync(x => x.Id == id);
            if (item == null) return NotFound();

            // Soft delete — real business data is never hard-deleted (see AuditableEntity.MarkDeleted).
            item.MarkDeleted();

            try
            {
                await db.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                return Conflict(new { message = "This OperatorStatement was already modified or deleted by another request." });
            }
            catch (DbUpdateException)
            {
                return Conflict(new { message = "Cannot delete this OperatorStatement — it is still referenced by other records." });
            }

            return NoContent();
        }

        private static OperatorStatementResponseDto ToResponseDto(OperatorStatement x) => new()
        {
            Id = x.Id,
            BusOperatorId = x.BusOperatorId,
            StatementNo = x.StatementNo,
            FromDate = x.FromDate,
            ToDate = x.ToDate,
            PlatformPayableToOperator = x.PlatformPayableToOperator,
            OperatorPayableToPlatform = x.OperatorPayableToPlatform,
            NetAmount = x.NetAmount,
            NetDirection = x.NetDirection,
            Status = x.Status,
            CreatedAtUtc = x.CreatedAtUtc,
            UpdatedAtUtc = x.UpdatedAtUtc,
            RowVersion = x.RowVersion,
        };
    }
}