// <auto-generated>
// Simple CRUD controller — generated so this entity is reachable/testable from Swagger + Postman.
// </auto-generated>

using TicketPortal.Api.Data;
using TicketPortal.Api.DTO;
using TicketPortal.Api.Models.Finance;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace TicketPortal.Api.Controllers
{
    [Authorize]
    [Route("api/[controller]")]
    [ApiController]
    public class OperatorPaymentReceiptsController(AppDbContext db) : ControllerBase
    {
        [HttpGet]
        public async Task<IActionResult> GetAll()
        {
            var items = await db.OperatorPaymentReceipts.ToListAsync();
            return Ok(items.Select(ToResponseDto));
        }

        [HttpGet("{id}")]
        public async Task<IActionResult> GetById(Guid id)
        {
            var item = await db.OperatorPaymentReceipts.FirstOrDefaultAsync(x => x.Id == id);
            return item == null ? NotFound() : Ok(ToResponseDto(item));
        }

        [HttpPost]
        public async Task<IActionResult> Create(OperatorPaymentReceiptCreateDto dto)
        {
            var item = new OperatorPaymentReceipt
            {
                OperatorInvoiceId = dto.OperatorInvoiceId,
                ReceivedAtUtc = dto.ReceivedAtUtc,
                Amount = dto.Amount,
                Currency = dto.Currency,
                ReferenceNo = dto.ReferenceNo,
                Notes = dto.Notes,
            };

            db.OperatorPaymentReceipts.Add(item);
            await db.SaveChangesAsync();

            return CreatedAtAction(nameof(GetById), new { id = item.Id }, ToResponseDto(item));
        }

        [HttpPut("{id}")]
        public async Task<IActionResult> Update(Guid id, OperatorPaymentReceiptUpdateDto dto)
        {
            var item = await db.OperatorPaymentReceipts.FirstOrDefaultAsync(x => x.Id == id);
            if (item == null) return NotFound(new { message = "OperatorPaymentReceipt not found." });

            if (dto.RowVersion == null || dto.RowVersion.Length == 0)
                return BadRequest(new { message = "RowVersion is required." });

            if (!item.RowVersion.SequenceEqual(dto.RowVersion))
            {
                return Conflict(new
                {
                    message = "This OperatorPaymentReceipt was changed by another request. Please GET the latest data and try again."
                });
            }

            db.Entry(item).Property(x => x.RowVersion).OriginalValue = dto.RowVersion;

            item.OperatorInvoiceId = dto.OperatorInvoiceId;
            item.ReceivedAtUtc = dto.ReceivedAtUtc;
            item.Amount = dto.Amount;
            item.Currency = dto.Currency;
            item.ReferenceNo = dto.ReferenceNo;
            item.Notes = dto.Notes;
            item.UpdatedAtUtc = DateTime.UtcNow;

            try
            {
                await db.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                return Conflict(new { message = "This OperatorPaymentReceipt was already modified or deleted by another request." });
            }
            catch (DbUpdateException ex)
            {
                var error = ex.InnerException?.InnerException?.Message ?? ex.InnerException?.Message ?? ex.Message;
                return Conflict(new { message = "Could not save OperatorPaymentReceipt.", details = error });
            }

            return Ok(ToResponseDto(item));
        }

        [HttpDelete("{id}")]
        public async Task<IActionResult> Delete(Guid id)
        {
            var item = await db.OperatorPaymentReceipts.FirstOrDefaultAsync(x => x.Id == id);
            if (item == null) return NotFound();

            // Soft delete — real business data is never hard-deleted (see AuditableEntity.MarkDeleted).
            item.MarkDeleted();

            try
            {
                await db.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                return Conflict(new { message = "This OperatorPaymentReceipt was already modified or deleted by another request." });
            }
            catch (DbUpdateException)
            {
                return Conflict(new { message = "Cannot delete this OperatorPaymentReceipt — it is still referenced by other records." });
            }

            return NoContent();
        }

        private static OperatorPaymentReceiptResponseDto ToResponseDto(OperatorPaymentReceipt x) => new()
        {
            Id = x.Id,
            OperatorInvoiceId = x.OperatorInvoiceId,
            ReceivedAtUtc = x.ReceivedAtUtc,
            Amount = x.Amount,
            Currency = x.Currency,
            ReferenceNo = x.ReferenceNo,
            Notes = x.Notes,
            CreatedAtUtc = x.CreatedAtUtc,
            UpdatedAtUtc = x.UpdatedAtUtc,
            RowVersion = x.RowVersion,
        };
    }
}