// <auto-generated>
// Simple CRUD controller — generated so this entity is reachable/testable from Swagger + Postman.
// </auto-generated>

using TicketPortal.Api.Data;
using TicketPortal.Api.DTO;
using TicketPortal.Api.Models.Finance;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace TicketPortal.Api.Controllers
{
    [Authorize]
    [Route("api/[controller]")]
    [ApiController]
    public class OperatorSettlementItemsController(AppDbContext db) : ControllerBase
    {
        [HttpGet]
        public async Task<IActionResult> GetAll()
        {
            var items = await db.OperatorSettlementItems.ToListAsync();
            return Ok(items.Select(ToResponseDto));
        }

        [HttpGet("{id}")]
        public async Task<IActionResult> GetById(Guid id)
        {
            var item = await db.OperatorSettlementItems.FirstOrDefaultAsync(x => x.Id == id);
            return item == null ? NotFound() : Ok(ToResponseDto(item));
        }

        [HttpPost]
        public async Task<IActionResult> Create(OperatorSettlementItemCreateDto dto)
        {
            var item = new OperatorSettlementItem
            {
                OperatorSettlementId = dto.OperatorSettlementId,
                BookingId = dto.BookingId,
                TicketId = dto.TicketId,
                PlatformLedgerId = dto.PlatformLedgerId,
                ItemType = dto.ItemType,
                SaleChannel = dto.SaleChannel,
                TicketFare = dto.TicketFare,
                PlatformCharge = dto.PlatformCharge,
                GatewayCharge = dto.GatewayCharge,
                RefundAmount = dto.RefundAmount,
                NetAmount = dto.NetAmount,
            };

            db.OperatorSettlementItems.Add(item);
            await db.SaveChangesAsync();

            return CreatedAtAction(nameof(GetById), new { id = item.Id }, ToResponseDto(item));
        }

        [HttpPut("{id}")]
        public async Task<IActionResult> Update(Guid id, OperatorSettlementItemUpdateDto dto)
        {
            var item = await db.OperatorSettlementItems.FirstOrDefaultAsync(x => x.Id == id);
            if (item == null) return NotFound(new { message = "OperatorSettlementItem not found." });

            if (dto.RowVersion == null || dto.RowVersion.Length == 0)
                return BadRequest(new { message = "RowVersion is required." });

            if (!item.RowVersion.SequenceEqual(dto.RowVersion))
            {
                return Conflict(new
                {
                    message = "This OperatorSettlementItem was changed by another request. Please GET the latest data and try again."
                });
            }

            db.Entry(item).Property(x => x.RowVersion).OriginalValue = dto.RowVersion;

            item.OperatorSettlementId = dto.OperatorSettlementId;
            item.BookingId = dto.BookingId;
            item.TicketId = dto.TicketId;
            item.PlatformLedgerId = dto.PlatformLedgerId;
            item.ItemType = dto.ItemType;
            item.SaleChannel = dto.SaleChannel;
            item.TicketFare = dto.TicketFare;
            item.PlatformCharge = dto.PlatformCharge;
            item.GatewayCharge = dto.GatewayCharge;
            item.RefundAmount = dto.RefundAmount;
            item.NetAmount = dto.NetAmount;
            item.UpdatedAtUtc = DateTime.UtcNow;

            try
            {
                await db.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                return Conflict(new { message = "This OperatorSettlementItem was already modified or deleted by another request." });
            }
            catch (DbUpdateException ex)
            {
                var error = ex.InnerException?.InnerException?.Message ?? ex.InnerException?.Message ?? ex.Message;
                return Conflict(new { message = "Could not save OperatorSettlementItem.", details = error });
            }

            return Ok(ToResponseDto(item));
        }

        [HttpDelete("{id}")]
        public async Task<IActionResult> Delete(Guid id)
        {
            var item = await db.OperatorSettlementItems.FirstOrDefaultAsync(x => x.Id == id);
            if (item == null) return NotFound();

            // Soft delete — real business data is never hard-deleted (see AuditableEntity.MarkDeleted).
            item.MarkDeleted();

            try
            {
                await db.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                return Conflict(new { message = "This OperatorSettlementItem was already modified or deleted by another request." });
            }
            catch (DbUpdateException)
            {
                return Conflict(new { message = "Cannot delete this OperatorSettlementItem — it is still referenced by other records." });
            }

            return NoContent();
        }

        private static OperatorSettlementItemResponseDto ToResponseDto(OperatorSettlementItem x) => new()
        {
            Id = x.Id,
            OperatorSettlementId = x.OperatorSettlementId,
            BookingId = x.BookingId,
            TicketId = x.TicketId,
            PlatformLedgerId = x.PlatformLedgerId,
            ItemType = x.ItemType,
            SaleChannel = x.SaleChannel,
            TicketFare = x.TicketFare,
            PlatformCharge = x.PlatformCharge,
            GatewayCharge = x.GatewayCharge,
            RefundAmount = x.RefundAmount,
            NetAmount = x.NetAmount,
            CreatedAtUtc = x.CreatedAtUtc,
            UpdatedAtUtc = x.UpdatedAtUtc,
            RowVersion = x.RowVersion,
        };
    }
}