// <auto-generated>
// Simple CRUD controller — generated so this entity is reachable/testable from Swagger + Postman.
// </auto-generated>

using TicketPortal.Api.Data;
using TicketPortal.Api.DTO;
using TicketPortal.Api.Models.Payments;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace TicketPortal.Api.Controllers
{
    [Authorize]
    [Route("api/[controller]")]
    [ApiController]
    public class PaymentProvidersController(AppDbContext db) : ControllerBase
    {
        [HttpGet]
        public async Task<IActionResult> GetAll()
        {
            var items = await db.PaymentProviders.ToListAsync();
            return Ok(items.Select(ToResponseDto));
        }

        [HttpGet("{id}")]
        public async Task<IActionResult> GetById(Guid id)
        {
            var item = await db.PaymentProviders.FirstOrDefaultAsync(x => x.Id == id);
            return item == null ? NotFound() : Ok(ToResponseDto(item));
        }

        [HttpPost]
        public async Task<IActionResult> Create(PaymentProviderCreateDto dto)
        {
            var item = new PaymentProvider
            {
                Name = dto.Name,
                Code = dto.Code,
                ProviderKind = dto.ProviderKind,
                Gateway = dto.Gateway,
                CheckoutBaseUrl = dto.CheckoutBaseUrl,
                WebhookUrl = dto.WebhookUrl,
                SupportsRefund = dto.SupportsRefund,
                IsActive = dto.IsActive,
            };

            db.PaymentProviders.Add(item);
            await db.SaveChangesAsync();

            return CreatedAtAction(nameof(GetById), new { id = item.Id }, ToResponseDto(item));
        }

        [HttpPut("{id}")]
        public async Task<IActionResult> Update(Guid id, PaymentProviderUpdateDto dto)
        {
            var item = await db.PaymentProviders.FirstOrDefaultAsync(x => x.Id == id);
            if (item == null) return NotFound(new { message = "PaymentProvider not found." });

            if (dto.RowVersion == null || dto.RowVersion.Length == 0)
                return BadRequest(new { message = "RowVersion is required." });

            if (!item.RowVersion.SequenceEqual(dto.RowVersion))
            {
                return Conflict(new
                {
                    message = "This PaymentProvider was changed by another request. Please GET the latest data and try again."
                });
            }

            db.Entry(item).Property(x => x.RowVersion).OriginalValue = dto.RowVersion;

            item.Name = dto.Name;
            item.Code = dto.Code;
            item.ProviderKind = dto.ProviderKind;
            item.Gateway = dto.Gateway;
            item.CheckoutBaseUrl = dto.CheckoutBaseUrl;
            item.WebhookUrl = dto.WebhookUrl;
            item.SupportsRefund = dto.SupportsRefund;
            item.IsActive = dto.IsActive;
            item.UpdatedAtUtc = DateTime.UtcNow;

            try
            {
                await db.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                return Conflict(new { message = "This PaymentProvider was already modified or deleted by another request." });
            }
            catch (DbUpdateException ex)
            {
                var error = ex.InnerException?.InnerException?.Message ?? ex.InnerException?.Message ?? ex.Message;
                return Conflict(new { message = "Could not save PaymentProvider.", details = error });
            }

            return Ok(ToResponseDto(item));
        }

        [HttpDelete("{id}")]
        public async Task<IActionResult> Delete(Guid id)
        {
            var item = await db.PaymentProviders.FirstOrDefaultAsync(x => x.Id == id);
            if (item == null) return NotFound();

            // Soft delete — real business data is never hard-deleted (see AuditableEntity.MarkDeleted).
            item.MarkDeleted();

            try
            {
                await db.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                return Conflict(new { message = "This PaymentProvider was already modified or deleted by another request." });
            }
            catch (DbUpdateException)
            {
                return Conflict(new { message = "Cannot delete this PaymentProvider — it is still referenced by other records." });
            }

            return NoContent();
        }

        private static PaymentProviderResponseDto ToResponseDto(PaymentProvider x) => new()
        {
            Id = x.Id,
            Name = x.Name,
            Code = x.Code,
            ProviderKind = x.ProviderKind,
            Gateway = x.Gateway,
            CheckoutBaseUrl = x.CheckoutBaseUrl,
            WebhookUrl = x.WebhookUrl,
            SupportsRefund = x.SupportsRefund,
            IsActive = x.IsActive,
            CreatedAtUtc = x.CreatedAtUtc,
            UpdatedAtUtc = x.UpdatedAtUtc,
            RowVersion = x.RowVersion,
        };
    }
}