// <auto-generated>
// Simple CRUD controller — generated so this entity is reachable/testable from Swagger + Postman.
// </auto-generated>

using TicketPortal.Api.Data;
using TicketPortal.Api.DTO;
using TicketPortal.Api.Models.Finance;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace TicketPortal.Api.Controllers
{
    [Authorize]
    [Route("api/[controller]")]
    [ApiController]
    public class PlatformLedgersController(AppDbContext db) : ControllerBase
    {
        [HttpGet]
        public async Task<IActionResult> GetAll()
        {
            var items = await db.PlatformLedgers.ToListAsync();
            return Ok(items.Select(ToResponseDto));
        }

        [HttpGet("{id}")]
        public async Task<IActionResult> GetById(Guid id)
        {
            var item = await db.PlatformLedgers.FirstOrDefaultAsync(x => x.Id == id);
            return item == null ? NotFound() : Ok(ToResponseDto(item));
        }

        [HttpPost]
        public async Task<IActionResult> Create(PlatformLedgerCreateDto dto)
        {
            var item = new PlatformLedger
            {
                BookingId = dto.BookingId,
                PaymentId = dto.PaymentId,
                RefundId = dto.RefundId,
                BusOperatorId = dto.BusOperatorId,
                OperatorSettlementId = dto.OperatorSettlementId,
                LedgerNo = dto.LedgerNo,
                ItemType = dto.ItemType,
                SaleChannel = dto.SaleChannel,
                DebitAmount = dto.DebitAmount,
                CreditAmount = dto.CreditAmount,
                Currency = dto.Currency,
                ReferenceNo = dto.ReferenceNo,
                Description = dto.Description,
            };

            db.PlatformLedgers.Add(item);
            await db.SaveChangesAsync();

            return CreatedAtAction(nameof(GetById), new { id = item.Id }, ToResponseDto(item));
        }

        [HttpPut("{id}")]
        public async Task<IActionResult> Update(Guid id, PlatformLedgerUpdateDto dto)
        {
            var item = await db.PlatformLedgers.FirstOrDefaultAsync(x => x.Id == id);
            if (item == null) return NotFound(new { message = "PlatformLedger not found." });

            if (dto.RowVersion == null || dto.RowVersion.Length == 0)
                return BadRequest(new { message = "RowVersion is required." });

            if (!item.RowVersion.SequenceEqual(dto.RowVersion))
            {
                return Conflict(new
                {
                    message = "This PlatformLedger was changed by another request. Please GET the latest data and try again."
                });
            }

            db.Entry(item).Property(x => x.RowVersion).OriginalValue = dto.RowVersion;

            item.BookingId = dto.BookingId;
            item.PaymentId = dto.PaymentId;
            item.RefundId = dto.RefundId;
            item.BusOperatorId = dto.BusOperatorId;
            item.OperatorSettlementId = dto.OperatorSettlementId;
            item.LedgerNo = dto.LedgerNo;
            item.ItemType = dto.ItemType;
            item.SaleChannel = dto.SaleChannel;
            item.DebitAmount = dto.DebitAmount;
            item.CreditAmount = dto.CreditAmount;
            item.Currency = dto.Currency;
            item.ReferenceNo = dto.ReferenceNo;
            item.Description = dto.Description;
            item.UpdatedAtUtc = DateTime.UtcNow;

            try
            {
                await db.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                return Conflict(new { message = "This PlatformLedger was already modified or deleted by another request." });
            }
            catch (DbUpdateException ex)
            {
                var error = ex.InnerException?.InnerException?.Message ?? ex.InnerException?.Message ?? ex.Message;
                return Conflict(new { message = "Could not save PlatformLedger.", details = error });
            }

            return Ok(ToResponseDto(item));
        }

        [HttpDelete("{id}")]
        public async Task<IActionResult> Delete(Guid id)
        {
            var item = await db.PlatformLedgers.FirstOrDefaultAsync(x => x.Id == id);
            if (item == null) return NotFound();

            // Soft delete — real business data is never hard-deleted (see AuditableEntity.MarkDeleted).
            item.MarkDeleted();

            try
            {
                await db.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                return Conflict(new { message = "This PlatformLedger was already modified or deleted by another request." });
            }
            catch (DbUpdateException)
            {
                return Conflict(new { message = "Cannot delete this PlatformLedger — it is still referenced by other records." });
            }

            return NoContent();
        }

        private static PlatformLedgerResponseDto ToResponseDto(PlatformLedger x) => new()
        {
            Id = x.Id,
            BookingId = x.BookingId,
            PaymentId = x.PaymentId,
            RefundId = x.RefundId,
            BusOperatorId = x.BusOperatorId,
            OperatorSettlementId = x.OperatorSettlementId,
            LedgerNo = x.LedgerNo,
            ItemType = x.ItemType,
            SaleChannel = x.SaleChannel,
            DebitAmount = x.DebitAmount,
            CreditAmount = x.CreditAmount,
            Currency = x.Currency,
            ReferenceNo = x.ReferenceNo,
            Description = x.Description,
            CreatedAtUtc = x.CreatedAtUtc,
            UpdatedAtUtc = x.UpdatedAtUtc,
            RowVersion = x.RowVersion,
        };
    }
}