// <auto-generated>
// Simple CRUD controller — generated so this entity is reachable/testable from Swagger + Postman.
// </auto-generated>

using TicketPortal.Api.Data;
using TicketPortal.Api.DTO;
using TicketPortal.Api.Models.People;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace TicketPortal.Api.Controllers
{
    [Authorize]
    [Route("api/[controller]")]
    [ApiController]
    public class SalesCountersController(AppDbContext db) : ControllerBase
    {
        [HttpGet]
        public async Task<IActionResult> GetAll()
        {
            var items = await db.SalesCounters.ToListAsync();
            return Ok(items.Select(ToResponseDto));
        }

        [HttpGet("{id}")]
        public async Task<IActionResult> GetById(Guid id)
        {
            var item = await db.SalesCounters.FirstOrDefaultAsync(x => x.Id == id);
            return item == null ? NotFound() : Ok(ToResponseDto(item));
        }

        [HttpPost]
        public async Task<IActionResult> Create(SalesCounterCreateDto dto)
        {
            var item = new SalesCounter
            {
                BusOperatorId = dto.BusOperatorId,
                TerminalId = dto.TerminalId,
                OperatorBranchId = dto.OperatorBranchId,
                CounterName = dto.CounterName,
                CounterCode = dto.CounterCode,
                PhoneNumber = dto.PhoneNumber,
                Address = dto.Address,
                IsActive = dto.IsActive,
            };

            db.SalesCounters.Add(item);
            await db.SaveChangesAsync();

            return CreatedAtAction(nameof(GetById), new { id = item.Id }, ToResponseDto(item));
        }

        [HttpPut("{id}")]
        public async Task<IActionResult> Update(Guid id, SalesCounterUpdateDto dto)
        {
            var item = await db.SalesCounters.FirstOrDefaultAsync(x => x.Id == id);
            if (item == null) return NotFound(new { message = "SalesCounter not found." });

            if (dto.RowVersion == null || dto.RowVersion.Length == 0)
                return BadRequest(new { message = "RowVersion is required." });

            if (!item.RowVersion.SequenceEqual(dto.RowVersion))
            {
                return Conflict(new
                {
                    message = "This SalesCounter was changed by another request. Please GET the latest data and try again."
                });
            }

            db.Entry(item).Property(x => x.RowVersion).OriginalValue = dto.RowVersion;

            item.BusOperatorId = dto.BusOperatorId;
            item.TerminalId = dto.TerminalId;
            item.OperatorBranchId = dto.OperatorBranchId;
            item.CounterName = dto.CounterName;
            item.CounterCode = dto.CounterCode;
            item.PhoneNumber = dto.PhoneNumber;
            item.Address = dto.Address;
            item.IsActive = dto.IsActive;
            item.UpdatedAtUtc = DateTime.UtcNow;

            try
            {
                await db.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                return Conflict(new { message = "This SalesCounter was already modified or deleted by another request." });
            }
            catch (DbUpdateException ex)
            {
                var error = ex.InnerException?.InnerException?.Message ?? ex.InnerException?.Message ?? ex.Message;
                return Conflict(new { message = "Could not save SalesCounter.", details = error });
            }

            return Ok(ToResponseDto(item));
        }

        [HttpDelete("{id}")]
        public async Task<IActionResult> Delete(Guid id)
        {
            var item = await db.SalesCounters.FirstOrDefaultAsync(x => x.Id == id);
            if (item == null) return NotFound();

            // Soft delete — real business data is never hard-deleted (see AuditableEntity.MarkDeleted).
            item.MarkDeleted();

            try
            {
                await db.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                return Conflict(new { message = "This SalesCounter was already modified or deleted by another request." });
            }
            catch (DbUpdateException)
            {
                return Conflict(new { message = "Cannot delete this SalesCounter — it is still referenced by other records." });
            }

            return NoContent();
        }

        private static SalesCounterResponseDto ToResponseDto(SalesCounter x) => new()
        {
            Id = x.Id,
            BusOperatorId = x.BusOperatorId,
            TerminalId = x.TerminalId,
            OperatorBranchId = x.OperatorBranchId,
            CounterName = x.CounterName,
            CounterCode = x.CounterCode,
            PhoneNumber = x.PhoneNumber,
            Address = x.Address,
            IsActive = x.IsActive,
            CreatedAtUtc = x.CreatedAtUtc,
            UpdatedAtUtc = x.UpdatedAtUtc,
            RowVersion = x.RowVersion,
        };
    }
}