// <auto-generated>
// Simple CRUD controller — generated so this entity is reachable/testable from Swagger + Postman.
// </auto-generated>

using TicketPortal.Api.Data;
using TicketPortal.Api.DTO;
using TicketPortal.Api.Models.Scheduling;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace TicketPortal.Api.Controllers
{
    [Authorize]
    [Route("api/[controller]")]
    [ApiController]
    public class SchedulesController(AppDbContext db) : ControllerBase
    {
        [HttpGet]
        public async Task<IActionResult> GetAll()
        {
            var items = await db.Schedules.ToListAsync();
            return Ok(items.Select(ToResponseDto));
        }

        [HttpGet("{id}")]
        public async Task<IActionResult> GetById(Guid id)
        {
            var item = await db.Schedules.FirstOrDefaultAsync(x => x.Id == id);
            return item == null ? NotFound() : Ok(ToResponseDto(item));
        }

        [HttpPost]
        public async Task<IActionResult> Create(ScheduleCreateDto dto)
        {
            var item = new Schedule
            {
                BusOperatorId = dto.BusOperatorId,
                BusRouteId = dto.BusRouteId,
                OperatorRouteId = dto.OperatorRouteId,
                BusId = dto.BusId,
                ScheduleCode = dto.ScheduleCode,
                DepartureTimeOfDay = dto.DepartureTimeOfDay,
                ArrivalTimeOfDay = dto.ArrivalTimeOfDay,
                OperatingDays = dto.OperatingDays,
                EffectiveFrom = dto.EffectiveFrom,
                EffectiveTo = dto.EffectiveTo,
                BaseFare = dto.BaseFare,
                Currency = dto.Currency,
                IsActive = dto.IsActive,
            };

            db.Schedules.Add(item);
            await db.SaveChangesAsync();

            return CreatedAtAction(nameof(GetById), new { id = item.Id }, ToResponseDto(item));
        }

        [HttpPut("{id}")]
        public async Task<IActionResult> Update(Guid id, ScheduleUpdateDto dto)
        {
            var item = await db.Schedules.FirstOrDefaultAsync(x => x.Id == id);
            if (item == null) return NotFound(new { message = "Schedule not found." });

            if (dto.RowVersion == null || dto.RowVersion.Length == 0)
                return BadRequest(new { message = "RowVersion is required." });

            if (!item.RowVersion.SequenceEqual(dto.RowVersion))
            {
                return Conflict(new
                {
                    message = "This Schedule was changed by another request. Please GET the latest data and try again."
                });
            }

            db.Entry(item).Property(x => x.RowVersion).OriginalValue = dto.RowVersion;

            item.BusOperatorId = dto.BusOperatorId;
            item.BusRouteId = dto.BusRouteId;
            item.OperatorRouteId = dto.OperatorRouteId;
            item.BusId = dto.BusId;
            item.ScheduleCode = dto.ScheduleCode;
            item.DepartureTimeOfDay = dto.DepartureTimeOfDay;
            item.ArrivalTimeOfDay = dto.ArrivalTimeOfDay;
            item.OperatingDays = dto.OperatingDays;
            item.EffectiveFrom = dto.EffectiveFrom;
            item.EffectiveTo = dto.EffectiveTo;
            item.BaseFare = dto.BaseFare;
            item.Currency = dto.Currency;
            item.IsActive = dto.IsActive;
            item.UpdatedAtUtc = DateTime.UtcNow;

            try
            {
                await db.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                return Conflict(new { message = "This Schedule was already modified or deleted by another request." });
            }
            catch (DbUpdateException ex)
            {
                var error = ex.InnerException?.InnerException?.Message ?? ex.InnerException?.Message ?? ex.Message;
                return Conflict(new { message = "Could not save Schedule.", details = error });
            }

            return Ok(ToResponseDto(item));
        }

        [HttpDelete("{id}")]
        public async Task<IActionResult> Delete(Guid id)
        {
            var item = await db.Schedules.FirstOrDefaultAsync(x => x.Id == id);
            if (item == null) return NotFound();

            // Soft delete — real business data is never hard-deleted (see AuditableEntity.MarkDeleted).
            item.MarkDeleted();

            try
            {
                await db.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                return Conflict(new { message = "This Schedule was already modified or deleted by another request." });
            }
            catch (DbUpdateException)
            {
                return Conflict(new { message = "Cannot delete this Schedule — it is still referenced by other records." });
            }

            return NoContent();
        }

        private static ScheduleResponseDto ToResponseDto(Schedule x) => new()
        {
            Id = x.Id,
            BusOperatorId = x.BusOperatorId,
            BusRouteId = x.BusRouteId,
            OperatorRouteId = x.OperatorRouteId,
            BusId = x.BusId,
            ScheduleCode = x.ScheduleCode,
            DepartureTimeOfDay = x.DepartureTimeOfDay,
            ArrivalTimeOfDay = x.ArrivalTimeOfDay,
            OperatingDays = x.OperatingDays,
            EffectiveFrom = x.EffectiveFrom,
            EffectiveTo = x.EffectiveTo,
            BaseFare = x.BaseFare,
            Currency = x.Currency,
            IsActive = x.IsActive,
            CreatedAtUtc = x.CreatedAtUtc,
            UpdatedAtUtc = x.UpdatedAtUtc,
            RowVersion = x.RowVersion,
        };
    }
}