// <auto-generated>
// Simple CRUD controller — generated so this entity is reachable/testable from Swagger + Postman.
// </auto-generated>

using TicketPortal.Api.Data;
using TicketPortal.Api.DTO;
using TicketPortal.Api.Models.Bookings;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace TicketPortal.Api.Controllers
{
    [Authorize]
    [Route("api/[controller]")]
    [ApiController]
    public class SeatHoldsController(AppDbContext db) : ControllerBase
    {
        [HttpGet]
        public async Task<IActionResult> GetAll()
        {
            var items = await db.SeatHolds.ToListAsync();
            return Ok(items.Select(ToResponseDto));
        }

        [HttpGet("{id}")]
        public async Task<IActionResult> GetById(Guid id)
        {
            var item = await db.SeatHolds.FirstOrDefaultAsync(x => x.Id == id);
            return item == null ? NotFound() : Ok(ToResponseDto(item));
        }

        [HttpPost]
        public async Task<IActionResult> Create(SeatHoldCreateDto dto)
        {
            var item = new SeatHold
            {
                TripId = dto.TripId,
                HeldByUserId = dto.HeldByUserId,
                HoldToken = dto.HoldToken,
                HoldStartedAtUtc = dto.HoldStartedAtUtc,
                HoldExpiresAtUtc = dto.HoldExpiresAtUtc,
                Status = dto.Status,
                ClientIpAddress = dto.ClientIpAddress,
                UserAgent = dto.UserAgent,
            };

            db.SeatHolds.Add(item);
            await db.SaveChangesAsync();

            return CreatedAtAction(nameof(GetById), new { id = item.Id }, ToResponseDto(item));
        }

        [HttpPut("{id}")]
        public async Task<IActionResult> Update(Guid id, SeatHoldUpdateDto dto)
        {
            var item = await db.SeatHolds.FirstOrDefaultAsync(x => x.Id == id);
            if (item == null) return NotFound(new { message = "SeatHold not found." });

            if (dto.RowVersion == null || dto.RowVersion.Length == 0)
                return BadRequest(new { message = "RowVersion is required." });

            if (!item.RowVersion.SequenceEqual(dto.RowVersion))
            {
                return Conflict(new
                {
                    message = "This SeatHold was changed by another request. Please GET the latest data and try again."
                });
            }

            db.Entry(item).Property(x => x.RowVersion).OriginalValue = dto.RowVersion;

            item.TripId = dto.TripId;
            item.HeldByUserId = dto.HeldByUserId;
            item.HoldToken = dto.HoldToken;
            item.HoldStartedAtUtc = dto.HoldStartedAtUtc;
            item.HoldExpiresAtUtc = dto.HoldExpiresAtUtc;
            item.Status = dto.Status;
            item.ClientIpAddress = dto.ClientIpAddress;
            item.UserAgent = dto.UserAgent;
            item.UpdatedAtUtc = DateTime.UtcNow;

            try
            {
                await db.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                return Conflict(new { message = "This SeatHold was already modified or deleted by another request." });
            }
            catch (DbUpdateException ex)
            {
                var error = ex.InnerException?.InnerException?.Message ?? ex.InnerException?.Message ?? ex.Message;
                return Conflict(new { message = "Could not save SeatHold.", details = error });
            }

            return Ok(ToResponseDto(item));
        }

        [HttpDelete("{id}")]
        public async Task<IActionResult> Delete(Guid id)
        {
            var item = await db.SeatHolds.FirstOrDefaultAsync(x => x.Id == id);
            if (item == null) return NotFound();

            // Soft delete — real business data is never hard-deleted (see AuditableEntity.MarkDeleted).
            item.MarkDeleted();

            try
            {
                await db.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                return Conflict(new { message = "This SeatHold was already modified or deleted by another request." });
            }
            catch (DbUpdateException)
            {
                return Conflict(new { message = "Cannot delete this SeatHold — it is still referenced by other records." });
            }

            return NoContent();
        }

        private static SeatHoldResponseDto ToResponseDto(SeatHold x) => new()
        {
            Id = x.Id,
            TripId = x.TripId,
            HeldByUserId = x.HeldByUserId,
            HoldToken = x.HoldToken,
            HoldStartedAtUtc = x.HoldStartedAtUtc,
            HoldExpiresAtUtc = x.HoldExpiresAtUtc,
            Status = x.Status,
            ClientIpAddress = x.ClientIpAddress,
            UserAgent = x.UserAgent,
            CreatedAtUtc = x.CreatedAtUtc,
            UpdatedAtUtc = x.UpdatedAtUtc,
            RowVersion = x.RowVersion,
        };
    }
}