// <auto-generated>
// Simple CRUD controller — generated so this entity is reachable/testable from Swagger + Postman.
// </auto-generated>

using TicketPortal.Api.Data;
using TicketPortal.Api.DTO;
using TicketPortal.Api.Models.People;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace TicketPortal.Api.Controllers
{
    [Authorize]
    [Route("api/[controller]")]
    [ApiController]
    public class StaffSalariesController(AppDbContext db) : ControllerBase
    {
        [HttpGet]
        public async Task<IActionResult> GetAll()
        {
            var items = await db.StaffSalaries.ToListAsync();
            return Ok(items.Select(ToResponseDto));
        }

        [HttpGet("{id}")]
        public async Task<IActionResult> GetById(Guid id)
        {
            var item = await db.StaffSalaries.FirstOrDefaultAsync(x => x.Id == id);
            return item == null ? NotFound() : Ok(ToResponseDto(item));
        }

        [HttpPost]
        public async Task<IActionResult> Create(StaffSalaryCreateDto dto)
        {
            var item = new StaffSalary
            {
                StaffProfileId = dto.StaffProfileId,
                PayPeriodStart = dto.PayPeriodStart,
                PayPeriodEnd = dto.PayPeriodEnd,
                Amount = dto.Amount,
                IsPaid = dto.IsPaid,
                PaidAtUtc = dto.PaidAtUtc,
                PaymentReference = dto.PaymentReference,
            };

            db.StaffSalaries.Add(item);
            await db.SaveChangesAsync();

            return CreatedAtAction(nameof(GetById), new { id = item.Id }, ToResponseDto(item));
        }

        [HttpPut("{id}")]
        public async Task<IActionResult> Update(Guid id, StaffSalaryUpdateDto dto)
        {
            var item = await db.StaffSalaries.FirstOrDefaultAsync(x => x.Id == id);
            if (item == null) return NotFound(new { message = "StaffSalary not found." });

            if (dto.RowVersion == null || dto.RowVersion.Length == 0)
                return BadRequest(new { message = "RowVersion is required." });

            if (!item.RowVersion.SequenceEqual(dto.RowVersion))
            {
                return Conflict(new
                {
                    message = "This StaffSalary was changed by another request. Please GET the latest data and try again."
                });
            }

            db.Entry(item).Property(x => x.RowVersion).OriginalValue = dto.RowVersion;

            item.StaffProfileId = dto.StaffProfileId;
            item.PayPeriodStart = dto.PayPeriodStart;
            item.PayPeriodEnd = dto.PayPeriodEnd;
            item.Amount = dto.Amount;
            item.IsPaid = dto.IsPaid;
            item.PaidAtUtc = dto.PaidAtUtc;
            item.PaymentReference = dto.PaymentReference;
            item.UpdatedAtUtc = DateTime.UtcNow;

            try
            {
                await db.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                return Conflict(new { message = "This StaffSalary was already modified or deleted by another request." });
            }
            catch (DbUpdateException ex)
            {
                var error = ex.InnerException?.InnerException?.Message ?? ex.InnerException?.Message ?? ex.Message;
                return Conflict(new { message = "Could not save StaffSalary.", details = error });
            }

            return Ok(ToResponseDto(item));
        }

        [HttpDelete("{id}")]
        public async Task<IActionResult> Delete(Guid id)
        {
            var item = await db.StaffSalaries.FirstOrDefaultAsync(x => x.Id == id);
            if (item == null) return NotFound();

            // Soft delete — real business data is never hard-deleted (see AuditableEntity.MarkDeleted).
            item.MarkDeleted();

            try
            {
                await db.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                return Conflict(new { message = "This StaffSalary was already modified or deleted by another request." });
            }
            catch (DbUpdateException)
            {
                return Conflict(new { message = "Cannot delete this StaffSalary — it is still referenced by other records." });
            }

            return NoContent();
        }

        private static StaffSalaryResponseDto ToResponseDto(StaffSalary x) => new()
        {
            Id = x.Id,
            StaffProfileId = x.StaffProfileId,
            PayPeriodStart = x.PayPeriodStart,
            PayPeriodEnd = x.PayPeriodEnd,
            Amount = x.Amount,
            IsPaid = x.IsPaid,
            PaidAtUtc = x.PaidAtUtc,
            PaymentReference = x.PaymentReference,
            CreatedAtUtc = x.CreatedAtUtc,
            UpdatedAtUtc = x.UpdatedAtUtc,
            RowVersion = x.RowVersion,
        };
    }
}