// <auto-generated>
// Simple CRUD controller — generated so this entity is reachable/testable from Swagger + Postman.
// </auto-generated>

using TicketPortal.Api.Data;
using TicketPortal.Api.DTO;
using TicketPortal.Api.Models.People;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace TicketPortal.Api.Controllers
{
    [Authorize]
    [Route("api/[controller]")]
    [ApiController]
    public class StaffProfilesController(AppDbContext db) : ControllerBase
    {
        [HttpGet]
        public async Task<IActionResult> GetAll()
        {
            var items = await db.StaffProfiles.ToListAsync();
            return Ok(items.Select(ToResponseDto));
        }

        [HttpGet("{id}")]
        public async Task<IActionResult> GetById(Guid id)
        {
            var item = await db.StaffProfiles.FirstOrDefaultAsync(x => x.Id == id);
            return item == null ? NotFound() : Ok(ToResponseDto(item));
        }

        [HttpPost]
        public async Task<IActionResult> Create(StaffProfileCreateDto dto)
        {
            var item = new StaffProfile
            {
                UserId = dto.UserId,
                BusOperatorId = dto.BusOperatorId,
                EmployeeCode = dto.EmployeeCode,
                Role = dto.Role,
                NationalIdNumber = dto.NationalIdNumber,
                JoiningDate = dto.JoiningDate,
                Address = dto.Address,
                TotalTripsCompleted = dto.TotalTripsCompleted,
                IsActive = dto.IsActive,
            };

            db.StaffProfiles.Add(item);
            await db.SaveChangesAsync();

            return CreatedAtAction(nameof(GetById), new { id = item.Id }, ToResponseDto(item));
        }

        [HttpPut("{id}")]
        public async Task<IActionResult> Update(Guid id, StaffProfileUpdateDto dto)
        {
            var item = await db.StaffProfiles.FirstOrDefaultAsync(x => x.Id == id);
            if (item == null) return NotFound(new { message = "StaffProfile not found." });

            if (dto.RowVersion == null || dto.RowVersion.Length == 0)
                return BadRequest(new { message = "RowVersion is required." });

            if (!item.RowVersion.SequenceEqual(dto.RowVersion))
            {
                return Conflict(new
                {
                    message = "This StaffProfile was changed by another request. Please GET the latest data and try again."
                });
            }

            db.Entry(item).Property(x => x.RowVersion).OriginalValue = dto.RowVersion;

            item.UserId = dto.UserId;
            item.BusOperatorId = dto.BusOperatorId;
            item.EmployeeCode = dto.EmployeeCode;
            item.Role = dto.Role;
            item.NationalIdNumber = dto.NationalIdNumber;
            item.JoiningDate = dto.JoiningDate;
            item.Address = dto.Address;
            item.TotalTripsCompleted = dto.TotalTripsCompleted;
            item.IsActive = dto.IsActive;
            item.UpdatedAtUtc = DateTime.UtcNow;

            try
            {
                await db.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                return Conflict(new { message = "This StaffProfile was already modified or deleted by another request." });
            }
            catch (DbUpdateException ex)
            {
                var error = ex.InnerException?.InnerException?.Message ?? ex.InnerException?.Message ?? ex.Message;
                return Conflict(new { message = "Could not save StaffProfile.", details = error });
            }

            return Ok(ToResponseDto(item));
        }

        [HttpDelete("{id}")]
        public async Task<IActionResult> Delete(Guid id)
        {
            var item = await db.StaffProfiles.FirstOrDefaultAsync(x => x.Id == id);
            if (item == null) return NotFound();

            // Soft delete — real business data is never hard-deleted (see AuditableEntity.MarkDeleted).
            item.MarkDeleted();

            try
            {
                await db.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                return Conflict(new { message = "This StaffProfile was already modified or deleted by another request." });
            }
            catch (DbUpdateException)
            {
                return Conflict(new { message = "Cannot delete this StaffProfile — it is still referenced by other records." });
            }

            return NoContent();
        }

        private static StaffProfileResponseDto ToResponseDto(StaffProfile x) => new()
        {
            Id = x.Id,
            UserId = x.UserId,
            BusOperatorId = x.BusOperatorId,
            EmployeeCode = x.EmployeeCode,
            Role = x.Role,
            NationalIdNumber = x.NationalIdNumber,
            JoiningDate = x.JoiningDate,
            Address = x.Address,
            TotalTripsCompleted = x.TotalTripsCompleted,
            IsActive = x.IsActive,
            CreatedAtUtc = x.CreatedAtUtc,
            UpdatedAtUtc = x.UpdatedAtUtc,
            RowVersion = x.RowVersion,
        };
    }
}