// <auto-generated>
// Simple CRUD controller — generated so this entity is reachable/testable from Swagger + Postman.
// </auto-generated>

using TicketPortal.Api.Data;
using TicketPortal.Api.DTO;
using TicketPortal.Api.Models.Bookings;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace TicketPortal.Api.Controllers
{
    [Authorize]
    [Route("api/[controller]")]
    [ApiController]
    public class TicketsController(AppDbContext db) : ControllerBase
    {
        [HttpGet]
        public async Task<IActionResult> GetAll()
        {
            var items = await db.Tickets.ToListAsync();
            return Ok(items.Select(ToResponseDto));
        }

        [HttpGet("{id}")]
        public async Task<IActionResult> GetById(Guid id)
        {
            var item = await db.Tickets.FirstOrDefaultAsync(x => x.Id == id);
            return item == null ? NotFound() : Ok(ToResponseDto(item));
        }

        [HttpPost]
        public async Task<IActionResult> Create(TicketCreateDto dto)
        {
            var item = new Ticket
            {
                BookingId = dto.BookingId,
                BookingPassengerId = dto.BookingPassengerId,
                TripId = dto.TripId,
                TripSeatId = dto.TripSeatId,
                TicketNumber = dto.TicketNumber,
                ExternalTicketKey = dto.ExternalTicketKey,
                SeatNumberSnapshot = dto.SeatNumberSnapshot,
                QrCodePayload = dto.QrCodePayload,
                Fare = dto.Fare,
                DiscountAmount = dto.DiscountAmount,
                FinalFare = dto.FinalFare,
                Status = dto.Status,
                IssuedAtUtc = dto.IssuedAtUtc,
                CheckedInAtUtc = dto.CheckedInAtUtc,
                CancelledAtUtc = dto.CancelledAtUtc,
            };

            db.Tickets.Add(item);
            await db.SaveChangesAsync();

            return CreatedAtAction(nameof(GetById), new { id = item.Id }, ToResponseDto(item));
        }

        [HttpPut("{id}")]
        public async Task<IActionResult> Update(Guid id, TicketUpdateDto dto)
        {
            var item = await db.Tickets.FirstOrDefaultAsync(x => x.Id == id);
            if (item == null) return NotFound(new { message = "Ticket not found." });

            if (dto.RowVersion == null || dto.RowVersion.Length == 0)
                return BadRequest(new { message = "RowVersion is required." });

            if (!item.RowVersion.SequenceEqual(dto.RowVersion))
            {
                return Conflict(new
                {
                    message = "This Ticket was changed by another request. Please GET the latest data and try again."
                });
            }

            db.Entry(item).Property(x => x.RowVersion).OriginalValue = dto.RowVersion;

            item.BookingId = dto.BookingId;
            item.BookingPassengerId = dto.BookingPassengerId;
            item.TripId = dto.TripId;
            item.TripSeatId = dto.TripSeatId;
            item.TicketNumber = dto.TicketNumber;
            item.ExternalTicketKey = dto.ExternalTicketKey;
            item.SeatNumberSnapshot = dto.SeatNumberSnapshot;
            item.QrCodePayload = dto.QrCodePayload;
            item.Fare = dto.Fare;
            item.DiscountAmount = dto.DiscountAmount;
            item.FinalFare = dto.FinalFare;
            item.Status = dto.Status;
            item.IssuedAtUtc = dto.IssuedAtUtc;
            item.CheckedInAtUtc = dto.CheckedInAtUtc;
            item.CancelledAtUtc = dto.CancelledAtUtc;
            item.UpdatedAtUtc = DateTime.UtcNow;

            try
            {
                await db.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                return Conflict(new { message = "This Ticket was already modified or deleted by another request." });
            }
            catch (DbUpdateException ex)
            {
                var error = ex.InnerException?.InnerException?.Message ?? ex.InnerException?.Message ?? ex.Message;
                return Conflict(new { message = "Could not save Ticket.", details = error });
            }

            return Ok(ToResponseDto(item));
        }

        [HttpDelete("{id}")]
        public async Task<IActionResult> Delete(Guid id)
        {
            var item = await db.Tickets.FirstOrDefaultAsync(x => x.Id == id);
            if (item == null) return NotFound();

            // Soft delete — real business data is never hard-deleted (see AuditableEntity.MarkDeleted).
            item.MarkDeleted();

            try
            {
                await db.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                return Conflict(new { message = "This Ticket was already modified or deleted by another request." });
            }
            catch (DbUpdateException)
            {
                return Conflict(new { message = "Cannot delete this Ticket — it is still referenced by other records." });
            }

            return NoContent();
        }

        private static TicketResponseDto ToResponseDto(Ticket x) => new()
        {
            Id = x.Id,
            BookingId = x.BookingId,
            BookingPassengerId = x.BookingPassengerId,
            TripId = x.TripId,
            TripSeatId = x.TripSeatId,
            TicketNumber = x.TicketNumber,
            ExternalTicketKey = x.ExternalTicketKey,
            SeatNumberSnapshot = x.SeatNumberSnapshot,
            QrCodePayload = x.QrCodePayload,
            Fare = x.Fare,
            DiscountAmount = x.DiscountAmount,
            FinalFare = x.FinalFare,
            Status = x.Status,
            IssuedAtUtc = x.IssuedAtUtc,
            CheckedInAtUtc = x.CheckedInAtUtc,
            CancelledAtUtc = x.CancelledAtUtc,
            CreatedAtUtc = x.CreatedAtUtc,
            UpdatedAtUtc = x.UpdatedAtUtc,
            RowVersion = x.RowVersion,
        };
    }
}