// <auto-generated>
// Generated to give every remaining entity a working CRUD API for Swagger/Postman.
// Simple flat Create/Update/Response DTOs — one-to-one with the entity's own scalar fields.
// </auto-generated>

using TicketPortal.Api.Models.Enums;
using System.ComponentModel.DataAnnotations;

namespace TicketPortal.Api.DTO
{
    public class CancellationRequestCreateDto
    {
        public Guid BookingId { get; set; }
        public Guid? TicketId { get; set; }
        public Guid? RequestedByUserId { get; set; }
        public Guid? ApprovedByUserId { get; set; }
        public CancellationRequestStatus Status { get; set; } = CancellationRequestStatus.Requested;
        public string Reason { get; set; } = string.Empty;
        public string? RejectedReason { get; set; }
        public decimal RequestedRefundAmount { get; set; }
        public decimal? ApprovedRefundAmount { get; set; }
        public DateTime RequestedAtUtc { get; set; } = DateTime.UtcNow;
        public DateTime? ApprovedAtUtc { get; set; }
        public DateTime? CompletedAtUtc { get; set; }
    }

    public class CancellationRequestUpdateDto : CancellationRequestCreateDto
    {
        // Required — optimistic-concurrency token, echo back what GET returned.
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();
    }

    public class CancellationRequestResponseDto
    {
        public Guid Id { get; set; }
        public Guid BookingId { get; set; }
        public Guid? TicketId { get; set; }
        public Guid? RequestedByUserId { get; set; }
        public Guid? ApprovedByUserId { get; set; }
        public CancellationRequestStatus Status { get; set; } = CancellationRequestStatus.Requested;
        public string Reason { get; set; } = string.Empty;
        public string? RejectedReason { get; set; }
        public decimal RequestedRefundAmount { get; set; }
        public decimal? ApprovedRefundAmount { get; set; }
        public DateTime RequestedAtUtc { get; set; } = DateTime.UtcNow;
        public DateTime? ApprovedAtUtc { get; set; }
        public DateTime? CompletedAtUtc { get; set; }
        public DateTime CreatedAtUtc { get; set; }
        public DateTime? UpdatedAtUtc { get; set; }
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();
    }

    // Everything about WHEN a hold starts/expires, its token, and its Status is decided by
    // SeatHoldService — never by the client. The client only says which seats it wants.
    public class SeatHoldCreateDto
    {
        public Guid TripId { get; set; }
        public List<Guid> TripSeatIds { get; set; } = new();
    }

    // No SeatHoldUpdateDto / raw PUT on purpose: a hold's Status only ever moves through
    // SeatHoldService (Create → hold, Release, or the expiry sweep) — see SeatHoldsController.

    public class SeatHoldResponseDto
    {
        public Guid Id { get; set; }
        public Guid TripId { get; set; }
        public Guid? HeldByUserId { get; set; }
        public string HoldToken { get; set; } = string.Empty;
        public DateTime HoldStartedAtUtc { get; set; } = DateTime.UtcNow;
        public DateTime HoldExpiresAtUtc { get; set; }
        public SeatHoldStatus Status { get; set; } = SeatHoldStatus.Active;

        // Convenience for the front-end's countdown timer — 0 once the hold is no longer Active.
        public int SecondsRemaining { get; set; }

        public string? ClientIpAddress { get; set; }
        public string? UserAgent { get; set; }
        public DateTime CreatedAtUtc { get; set; }
        public DateTime? UpdatedAtUtc { get; set; }
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();
    }

    // No Create/Update DTO for SeatHoldItem: items are written only as a side effect of
    // SeatHoldService.HoldSeatsAsync. SeatHoldItemsController is read-only.
    public class SeatHoldItemResponseDto
    {
        public Guid Id { get; set; }
        public Guid SeatHoldId { get; set; }
        public Guid TripSeatId { get; set; }
        public decimal FareAtHold { get; set; }
        public DateTime CreatedAtUtc { get; set; }
        public DateTime? UpdatedAtUtc { get; set; }
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();
    }

    // No Create/Update DTO for Ticket: tickets are issued only by PaymentConfirmationService
    // the moment an online payment is confirmed. TicketsController is read-only.
    public class TicketResponseDto
    {
        public Guid Id { get; set; }
        public Guid BookingId { get; set; }
        public Guid BookingPassengerId { get; set; }
        public Guid TripId { get; set; }
        public Guid TripSeatId { get; set; }
        public string TicketNumber { get; set; } = string.Empty;
        public string? ExternalTicketKey { get; set; }
        public string SeatNumberSnapshot { get; set; } = string.Empty;
        public string QrCodePayload { get; set; } = string.Empty;
        public decimal Fare { get; set; }
        public decimal DiscountAmount { get; set; }
        public decimal FinalFare { get; set; }
        public TicketStatus Status { get; set; } = TicketStatus.PendingPayment;
        public DateTime? IssuedAtUtc { get; set; }
        public DateTime? CheckedInAtUtc { get; set; }
        public DateTime? CancelledAtUtc { get; set; }
        public DateTime CreatedAtUtc { get; set; }
        public DateTime? UpdatedAtUtc { get; set; }
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();
    }

}