// <auto-generated>
// Generated to give every remaining entity a working CRUD API for Swagger/Postman.
// Simple flat Create/Update/Response DTOs — one-to-one with the entity's own scalar fields.
// </auto-generated>

using TicketPortal.Api.Models.Enums;
using System.ComponentModel.DataAnnotations;

namespace TicketPortal.Api.DTO
{
    public class CancellationRequestCreateDto
    {
        public Guid BookingId { get; set; }
        public Guid? TicketId { get; set; }
        public Guid? RequestedByUserId { get; set; }
        public Guid? ApprovedByUserId { get; set; }
        public CancellationRequestStatus Status { get; set; } = CancellationRequestStatus.Requested;
        public string Reason { get; set; } = string.Empty;
        public string? RejectedReason { get; set; }
        public decimal RequestedRefundAmount { get; set; }
        public decimal? ApprovedRefundAmount { get; set; }
        public DateTime RequestedAtUtc { get; set; } = DateTime.UtcNow;
        public DateTime? ApprovedAtUtc { get; set; }
        public DateTime? CompletedAtUtc { get; set; }
    }

    public class CancellationRequestUpdateDto : CancellationRequestCreateDto
    {
        // Required — optimistic-concurrency token, echo back what GET returned.
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();
    }

    public class CancellationRequestResponseDto
    {
        public Guid Id { get; set; }
        public Guid BookingId { get; set; }
        public Guid? TicketId { get; set; }
        public Guid? RequestedByUserId { get; set; }
        public Guid? ApprovedByUserId { get; set; }
        public CancellationRequestStatus Status { get; set; } = CancellationRequestStatus.Requested;
        public string Reason { get; set; } = string.Empty;
        public string? RejectedReason { get; set; }
        public decimal RequestedRefundAmount { get; set; }
        public decimal? ApprovedRefundAmount { get; set; }
        public DateTime RequestedAtUtc { get; set; } = DateTime.UtcNow;
        public DateTime? ApprovedAtUtc { get; set; }
        public DateTime? CompletedAtUtc { get; set; }
        public DateTime CreatedAtUtc { get; set; }
        public DateTime? UpdatedAtUtc { get; set; }
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();
    }

    public class SeatHoldCreateDto
    {
        public Guid TripId { get; set; }
        public Guid? HeldByUserId { get; set; }
        public string HoldToken { get; set; } = string.Empty;
        public DateTime HoldStartedAtUtc { get; set; } = DateTime.UtcNow;
        public DateTime HoldExpiresAtUtc { get; set; }
        public SeatHoldStatus Status { get; set; } = SeatHoldStatus.Active;
        public string? ClientIpAddress { get; set; }
        public string? UserAgent { get; set; }
    }

    public class SeatHoldUpdateDto : SeatHoldCreateDto
    {
        // Required — optimistic-concurrency token, echo back what GET returned.
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();
    }

    public class SeatHoldResponseDto
    {
        public Guid Id { get; set; }
        public Guid TripId { get; set; }
        public Guid? HeldByUserId { get; set; }
        public string HoldToken { get; set; } = string.Empty;
        public DateTime HoldStartedAtUtc { get; set; } = DateTime.UtcNow;
        public DateTime HoldExpiresAtUtc { get; set; }
        public SeatHoldStatus Status { get; set; } = SeatHoldStatus.Active;
        public string? ClientIpAddress { get; set; }
        public string? UserAgent { get; set; }
        public DateTime CreatedAtUtc { get; set; }
        public DateTime? UpdatedAtUtc { get; set; }
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();
    }

    public class SeatHoldItemCreateDto
    {
        public Guid SeatHoldId { get; set; }
        public Guid TripSeatId { get; set; }
        public decimal FareAtHold { get; set; }
    }

    public class SeatHoldItemUpdateDto : SeatHoldItemCreateDto
    {
        // Required — optimistic-concurrency token, echo back what GET returned.
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();
    }

    public class SeatHoldItemResponseDto
    {
        public Guid Id { get; set; }
        public Guid SeatHoldId { get; set; }
        public Guid TripSeatId { get; set; }
        public decimal FareAtHold { get; set; }
        public DateTime CreatedAtUtc { get; set; }
        public DateTime? UpdatedAtUtc { get; set; }
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();
    }

    public class TicketCreateDto
    {
        public Guid BookingId { get; set; }
        public Guid BookingPassengerId { get; set; }
        public Guid TripId { get; set; }
        public Guid TripSeatId { get; set; }
        public string TicketNumber { get; set; } = string.Empty;
        public string? ExternalTicketKey { get; set; }
        public string SeatNumberSnapshot { get; set; } = string.Empty;
        public string QrCodePayload { get; set; } = string.Empty;
        public decimal Fare { get; set; }
        public decimal DiscountAmount { get; set; }
        public decimal FinalFare { get; set; }
        public TicketStatus Status { get; set; } = TicketStatus.PendingPayment;
        public DateTime? IssuedAtUtc { get; set; }
        public DateTime? CheckedInAtUtc { get; set; }
        public DateTime? CancelledAtUtc { get; set; }
    }

    public class TicketUpdateDto : TicketCreateDto
    {
        // Required — optimistic-concurrency token, echo back what GET returned.
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();
    }

    public class TicketResponseDto
    {
        public Guid Id { get; set; }
        public Guid BookingId { get; set; }
        public Guid BookingPassengerId { get; set; }
        public Guid TripId { get; set; }
        public Guid TripSeatId { get; set; }
        public string TicketNumber { get; set; } = string.Empty;
        public string? ExternalTicketKey { get; set; }
        public string SeatNumberSnapshot { get; set; } = string.Empty;
        public string QrCodePayload { get; set; } = string.Empty;
        public decimal Fare { get; set; }
        public decimal DiscountAmount { get; set; }
        public decimal FinalFare { get; set; }
        public TicketStatus Status { get; set; } = TicketStatus.PendingPayment;
        public DateTime? IssuedAtUtc { get; set; }
        public DateTime? CheckedInAtUtc { get; set; }
        public DateTime? CancelledAtUtc { get; set; }
        public DateTime CreatedAtUtc { get; set; }
        public DateTime? UpdatedAtUtc { get; set; }
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();
    }

}