// <auto-generated>
// Generated to give every remaining entity a working CRUD API for Swagger/Postman.
// Simple flat Create/Update/Response DTOs — one-to-one with the entity's own scalar fields.
// </auto-generated>

using TicketPortal.Api.Models.Enums;
using System.ComponentModel.DataAnnotations;

namespace TicketPortal.Api.DTO
{
    public class BusRouteCreateDto
    {
        public Guid OriginTerminalId { get; set; }
        public Guid DestinationTerminalId { get; set; }
        public Guid? ReverseRouteId { get; set; }
        public string RouteCode { get; set; } = string.Empty;
        public string Name { get; set; } = string.Empty;
        public decimal DistanceKm { get; set; }
        public int EstimatedDurationMinutes { get; set; }
        public decimal? DefaultBaseFare { get; set; }
        public bool IsActive { get; set; } = true;
    }

    public class BusRouteUpdateDto : BusRouteCreateDto
    {
        // Required — optimistic-concurrency token, echo back what GET returned.
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();
    }

    public class BusRouteResponseDto
    {
        public Guid Id { get; set; }
        public Guid OriginTerminalId { get; set; }
        public Guid DestinationTerminalId { get; set; }
        public Guid? ReverseRouteId { get; set; }
        public string RouteCode { get; set; } = string.Empty;
        public string Name { get; set; } = string.Empty;
        public decimal DistanceKm { get; set; }
        public int EstimatedDurationMinutes { get; set; }
        public decimal? DefaultBaseFare { get; set; }
        public bool IsActive { get; set; } = true;
        public DateTime CreatedAtUtc { get; set; }
        public DateTime? UpdatedAtUtc { get; set; }
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();
    }

    public class OperatorBranchCreateDto
    {
        public Guid BusOperatorId { get; set; }
        public string BranchName { get; set; } = string.Empty;
        public string Address { get; set; } = string.Empty;
        public string Phone { get; set; } = string.Empty;
        public string City { get; set; } = string.Empty;
        public string District { get; set; } = string.Empty;
    }

    public class OperatorBranchUpdateDto : OperatorBranchCreateDto
    {
        // Required — optimistic-concurrency token, echo back what GET returned.
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();
    }

    public class OperatorBranchResponseDto
    {
        public Guid Id { get; set; }
        public Guid BusOperatorId { get; set; }
        public string BranchName { get; set; } = string.Empty;
        public string Address { get; set; } = string.Empty;
        public string Phone { get; set; } = string.Empty;
        public string City { get; set; } = string.Empty;
        public string District { get; set; } = string.Empty;
        public DateTime CreatedAtUtc { get; set; }
        public DateTime? UpdatedAtUtc { get; set; }
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();
    }

    public class OperatorRouteStopCreateDto
    {
        public Guid OperatorRouteId { get; set; }
        public Guid TerminalId { get; set; }
        public int StopOrder { get; set; }
        public int? ArrivalOffsetMinutes { get; set; }
        public int? DepartureOffsetMinutes { get; set; }
        public bool IsPickupPoint { get; set; } = true;
        public bool IsDropOffPoint { get; set; } = true;
        public string? ExternalStopKey { get; set; }
    }

    public class OperatorRouteStopUpdateDto : OperatorRouteStopCreateDto
    {
        // Required — optimistic-concurrency token, echo back what GET returned.
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();
    }

    public class OperatorRouteStopResponseDto
    {
        public Guid Id { get; set; }
        public Guid OperatorRouteId { get; set; }
        public Guid TerminalId { get; set; }
        public int StopOrder { get; set; }
        public int? ArrivalOffsetMinutes { get; set; }
        public int? DepartureOffsetMinutes { get; set; }
        public bool IsPickupPoint { get; set; } = true;
        public bool IsDropOffPoint { get; set; } = true;
        public string? ExternalStopKey { get; set; }
        public DateTime CreatedAtUtc { get; set; }
        public DateTime? UpdatedAtUtc { get; set; }
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();
    }

    public class OperatorSettingCreateDto
    {
        public Guid BusOperatorId { get; set; }
        public string Key { get; set; } = string.Empty;
        public string Value { get; set; } = string.Empty;
        public string? Description { get; set; }
    }

    public class OperatorSettingUpdateDto : OperatorSettingCreateDto
    {
        // Required — optimistic-concurrency token, echo back what GET returned.
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();
    }

    public class OperatorSettingResponseDto
    {
        public Guid Id { get; set; }
        public Guid BusOperatorId { get; set; }
        public string Key { get; set; } = string.Empty;
        public string Value { get; set; } = string.Empty;
        public string? Description { get; set; }
        public DateTime CreatedAtUtc { get; set; }
        public DateTime? UpdatedAtUtc { get; set; }
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();
    }

    public class RouteStopCreateDto
    {
        public Guid BusRouteId { get; set; }
        public Guid TerminalId { get; set; }
        public int StopOrder { get; set; }
        public int? ArrivalOffsetMinutes { get; set; }
        public int? DepartureOffsetMinutes { get; set; }
        public decimal DistanceFromOriginKm { get; set; }
        public bool IsPickupPoint { get; set; } = true;
        public bool IsDropOffPoint { get; set; } = true;
    }

    public class RouteStopUpdateDto : RouteStopCreateDto
    {
        // Required — optimistic-concurrency token, echo back what GET returned.
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();
    }

    public class RouteStopResponseDto
    {
        public Guid Id { get; set; }
        public Guid BusRouteId { get; set; }
        public Guid TerminalId { get; set; }
        public int StopOrder { get; set; }
        public int? ArrivalOffsetMinutes { get; set; }
        public int? DepartureOffsetMinutes { get; set; }
        public decimal DistanceFromOriginKm { get; set; }
        public bool IsPickupPoint { get; set; } = true;
        public bool IsDropOffPoint { get; set; } = true;
        public DateTime CreatedAtUtc { get; set; }
        public DateTime? UpdatedAtUtc { get; set; }
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();
    }

    public class TerminalCreateDto
    {
        public string Name { get; set; } = string.Empty;
        public string Code { get; set; } = string.Empty;
        public string City { get; set; } = string.Empty;
        public string District { get; set; } = string.Empty;
        public string Division { get; set; } = string.Empty;
        public string Country { get; set; } = "Bangladesh";
        public string Address { get; set; } = string.Empty;
        public decimal? Latitude { get; set; }
        public decimal? Longitude { get; set; }
        public bool IsActive { get; set; } = true;
    }

    public class TerminalUpdateDto : TerminalCreateDto
    {
        // Required — optimistic-concurrency token, echo back what GET returned.
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();
    }

    public class TerminalResponseDto
    {
        public Guid Id { get; set; }
        public string Name { get; set; } = string.Empty;
        public string Code { get; set; } = string.Empty;
        public string City { get; set; } = string.Empty;
        public string District { get; set; } = string.Empty;
        public string Division { get; set; } = string.Empty;
        public string Country { get; set; } = "Bangladesh";
        public string Address { get; set; } = string.Empty;
        public decimal? Latitude { get; set; }
        public decimal? Longitude { get; set; }
        public bool IsActive { get; set; } = true;
        public DateTime CreatedAtUtc { get; set; }
        public DateTime? UpdatedAtUtc { get; set; }
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();
    }

}