// <auto-generated>
// Generated to give every remaining entity a working CRUD API for Swagger/Postman.
// Simple flat Create/Update/Response DTOs — one-to-one with the entity's own scalar fields.
// </auto-generated>

using TicketPortal.Api.Models.Enums;
using System.ComponentModel.DataAnnotations;

namespace TicketPortal.Api.DTO
{
    public class ActivityLogCreateDto
    {
        public Guid? UserId { get; set; }
        public string Action { get; set; } = string.Empty;
        public string? EntityName { get; set; }
        public string? EntityId { get; set; }
        public string? IpAddress { get; set; }
    }

    public class ActivityLogUpdateDto : ActivityLogCreateDto
    {
        // Required — optimistic-concurrency token, echo back what GET returned.
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();
    }

    public class ActivityLogResponseDto
    {
        public Guid Id { get; set; }
        public Guid? UserId { get; set; }
        public string Action { get; set; } = string.Empty;
        public string? EntityName { get; set; }
        public string? EntityId { get; set; }
        public string? IpAddress { get; set; }
        public DateTime CreatedAtUtc { get; set; }
        public DateTime? UpdatedAtUtc { get; set; }
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();
    }

    public class AuditLogCreateDto
    {
        public Guid? UserId { get; set; }
        public string EntityName { get; set; } = string.Empty;
        public string EntityId { get; set; } = string.Empty;
        public string Action { get; set; } = string.Empty;
        public string? OldValuesJson { get; set; }
        public string? NewValuesJson { get; set; }
        public string? IpAddress { get; set; }
        public string? UserAgent { get; set; }
        public DateTime CreatedAtUtc { get; set; } = DateTime.UtcNow;
    }

    public class AuditLogUpdateDto : AuditLogCreateDto
    {
    }

    public class AuditLogResponseDto
    {
        public Guid Id { get; set; }
        public Guid? UserId { get; set; }
        public string EntityName { get; set; } = string.Empty;
        public string EntityId { get; set; } = string.Empty;
        public string Action { get; set; } = string.Empty;
        public string? OldValuesJson { get; set; }
        public string? NewValuesJson { get; set; }
        public string? IpAddress { get; set; }
        public string? UserAgent { get; set; }
        public DateTime CreatedAtUtc { get; set; } = DateTime.UtcNow;
    }

    public class LoginHistoryCreateDto
    {
        public Guid UserId { get; set; }
        public DateTime LoginAtUtc { get; set; } = DateTime.UtcNow;
        public string? IpAddress { get; set; }
        public string? UserAgent { get; set; }
        public bool Success { get; set; }
    }

    public class LoginHistoryUpdateDto : LoginHistoryCreateDto
    {
    }

    public class LoginHistoryResponseDto
    {
        public Guid Id { get; set; }
        public Guid UserId { get; set; }
        public DateTime LoginAtUtc { get; set; } = DateTime.UtcNow;
        public string? IpAddress { get; set; }
        public string? UserAgent { get; set; }
        public bool Success { get; set; }
    }

    public class NotificationLogCreateDto
    {
        public Guid? BookingId { get; set; }
        public Guid? TicketId { get; set; }
        public Guid? UserId { get; set; }
        public NotificationChannel Channel { get; set; }
        public string Recipient { get; set; } = string.Empty;
        public string? Subject { get; set; }
        public string Message { get; set; } = string.Empty;
        public NotificationStatus Status { get; set; } = NotificationStatus.Queued;
        public string? ProviderMessageId { get; set; }
        public string? ErrorMessage { get; set; }
        public DateTime? SentAtUtc { get; set; }
    }

    public class NotificationLogUpdateDto : NotificationLogCreateDto
    {
        // Required — optimistic-concurrency token, echo back what GET returned.
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();
    }

    public class NotificationLogResponseDto
    {
        public Guid Id { get; set; }
        public Guid? BookingId { get; set; }
        public Guid? TicketId { get; set; }
        public Guid? UserId { get; set; }
        public NotificationChannel Channel { get; set; }
        public string Recipient { get; set; } = string.Empty;
        public string? Subject { get; set; }
        public string Message { get; set; } = string.Empty;
        public NotificationStatus Status { get; set; } = NotificationStatus.Queued;
        public string? ProviderMessageId { get; set; }
        public string? ErrorMessage { get; set; }
        public DateTime? SentAtUtc { get; set; }
        public DateTime CreatedAtUtc { get; set; }
        public DateTime? UpdatedAtUtc { get; set; }
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();
    }

}