// <auto-generated>
// Generated to give every remaining entity a working CRUD API for Swagger/Postman.
// Simple flat Create/Update/Response DTOs — one-to-one with the entity's own scalar fields.
// </auto-generated>

using TicketPortal.Api.Models.Enums;
using System.ComponentModel.DataAnnotations;

namespace TicketPortal.Api.DTO
{
    public class AgentCreateDto
    {
        public Guid? BusOperatorId { get; set; }
        public string Name { get; set; } = string.Empty;
        public string AgencyCode { get; set; } = string.Empty;
        public string ContactPerson { get; set; } = string.Empty;
        public string PhoneNumber { get; set; } = string.Empty;
        public string? Email { get; set; }
        public string Address { get; set; } = string.Empty;
        public decimal CommissionPercentage { get; set; }
        public bool IsActive { get; set; } = true;
    }

    public class AgentUpdateDto : AgentCreateDto
    {
        // Required — optimistic-concurrency token, echo back what GET returned.
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();
    }

    public class AgentResponseDto
    {
        public Guid Id { get; set; }
        public Guid? BusOperatorId { get; set; }
        public string Name { get; set; } = string.Empty;
        public string AgencyCode { get; set; } = string.Empty;
        public string ContactPerson { get; set; } = string.Empty;
        public string PhoneNumber { get; set; } = string.Empty;
        public string? Email { get; set; }
        public string Address { get; set; } = string.Empty;
        public decimal CommissionPercentage { get; set; }
        public bool IsActive { get; set; } = true;
        public DateTime CreatedAtUtc { get; set; }
        public DateTime? UpdatedAtUtc { get; set; }
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();
    }

    public class CustomerAddressCreateDto
    {
        public Guid CustomerProfileId { get; set; }
        public string Label { get; set; } = string.Empty;
        public string AddressLine { get; set; } = string.Empty;
        public string City { get; set; } = string.Empty;
        public string District { get; set; } = string.Empty;
        public string Country { get; set; } = "Bangladesh";
        public bool IsDefault { get; set; }
    }

    public class CustomerAddressUpdateDto : CustomerAddressCreateDto
    {
        // Required — optimistic-concurrency token, echo back what GET returned.
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();
    }

    public class CustomerAddressResponseDto
    {
        public Guid Id { get; set; }
        public Guid CustomerProfileId { get; set; }
        public string Label { get; set; } = string.Empty;
        public string AddressLine { get; set; } = string.Empty;
        public string City { get; set; } = string.Empty;
        public string District { get; set; } = string.Empty;
        public string Country { get; set; } = "Bangladesh";
        public bool IsDefault { get; set; }
        public DateTime CreatedAtUtc { get; set; }
        public DateTime? UpdatedAtUtc { get; set; }
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();
    }

    public class CustomerProfileCreateDto
    {
        public Guid UserId { get; set; }
        public string? NationalIdNumber { get; set; }
        public DateOnly? DateOfBirth { get; set; }
        public Gender Gender { get; set; } = Gender.Unknown;
        public string? EmergencyContactPhone { get; set; }
        public decimal WalletBalance { get; set; }
        public string? PreferredLanguageCode { get; set; }
    }

    public class CustomerProfileUpdateDto : CustomerProfileCreateDto
    {
        // Required — optimistic-concurrency token, echo back what GET returned.
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();
    }

    public class CustomerProfileResponseDto
    {
        public Guid Id { get; set; }
        public Guid UserId { get; set; }
        public string? NationalIdNumber { get; set; }
        public DateOnly? DateOfBirth { get; set; }
        public Gender Gender { get; set; } = Gender.Unknown;
        public string? EmergencyContactPhone { get; set; }
        public decimal WalletBalance { get; set; }
        public string? PreferredLanguageCode { get; set; }
        public DateTime CreatedAtUtc { get; set; }
        public DateTime? UpdatedAtUtc { get; set; }
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();
    }

    // No Create/Update DTO: CustomerWalletService.CreditAsync/DebitAsync is the only writer,
    // and it always writes the balance change and this row together. CustomerWalletTransactionsController
    // is read-only.
    public class CustomerWalletTransactionResponseDto
    {
        public Guid Id { get; set; }
        public Guid CustomerProfileId { get; set; }
        public Guid? BookingId { get; set; }
        public Guid? RefundId { get; set; }
        public CustomerWalletTransactionType TransactionType { get; set; }
        public decimal Amount { get; set; }
        public decimal BalanceAfter { get; set; }
        public string Currency { get; set; } = "BDT";
        public string? Description { get; set; }
        public DateTime CreatedAtUtc { get; set; }
        public DateTime? UpdatedAtUtc { get; set; }
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();
    }

    public class DriverLicenseCreateDto
    {
        public Guid StaffProfileId { get; set; }
        public string LicenseNumber { get; set; } = string.Empty;
        public LicenseType Type { get; set; }
        public DateOnly IssueDate { get; set; }
        public DateOnly ExpiryDate { get; set; }
    }

    public class DriverLicenseUpdateDto : DriverLicenseCreateDto
    {
        // Required — optimistic-concurrency token, echo back what GET returned.
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();
    }

    public class DriverLicenseResponseDto
    {
        public Guid Id { get; set; }
        public Guid StaffProfileId { get; set; }
        public string LicenseNumber { get; set; } = string.Empty;
        public LicenseType Type { get; set; }
        public DateOnly IssueDate { get; set; }
        public DateOnly ExpiryDate { get; set; }
        public DateTime CreatedAtUtc { get; set; }
        public DateTime? UpdatedAtUtc { get; set; }
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();
    }

    public class EmergencyContactCreateDto
    {
        public Guid CustomerProfileId { get; set; }
        public string Name { get; set; } = string.Empty;
        public string Phone { get; set; } = string.Empty;
        public string? Relation { get; set; }
    }

    public class EmergencyContactUpdateDto : EmergencyContactCreateDto
    {
        // Required — optimistic-concurrency token, echo back what GET returned.
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();
    }

    public class EmergencyContactResponseDto
    {
        public Guid Id { get; set; }
        public Guid CustomerProfileId { get; set; }
        public string Name { get; set; } = string.Empty;
        public string Phone { get; set; } = string.Empty;
        public string? Relation { get; set; }
        public DateTime CreatedAtUtc { get; set; }
        public DateTime? UpdatedAtUtc { get; set; }
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();
    }

    public class SalesCounterCreateDto
    {
        public Guid BusOperatorId { get; set; }
        public Guid TerminalId { get; set; }
        public Guid? OperatorBranchId { get; set; }
        public string CounterName { get; set; } = string.Empty;
        public string CounterCode { get; set; } = string.Empty;
        public string PhoneNumber { get; set; } = string.Empty;
        public string Address { get; set; } = string.Empty;
        public bool IsActive { get; set; } = true;
    }

    public class SalesCounterUpdateDto : SalesCounterCreateDto
    {
        // Required — optimistic-concurrency token, echo back what GET returned.
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();
    }

    public class SalesCounterResponseDto
    {
        public Guid Id { get; set; }
        public Guid BusOperatorId { get; set; }
        public Guid TerminalId { get; set; }
        public Guid? OperatorBranchId { get; set; }
        public string CounterName { get; set; } = string.Empty;
        public string CounterCode { get; set; } = string.Empty;
        public string PhoneNumber { get; set; } = string.Empty;
        public string Address { get; set; } = string.Empty;
        public bool IsActive { get; set; } = true;
        public DateTime CreatedAtUtc { get; set; }
        public DateTime? UpdatedAtUtc { get; set; }
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();
    }

    public class StaffAttendanceCreateDto
    {
        public Guid StaffProfileId { get; set; }
        public DateOnly AttendanceDate { get; set; }
        public AttendanceStatus Status { get; set; }
        public string? Remarks { get; set; }
    }

    public class StaffAttendanceUpdateDto : StaffAttendanceCreateDto
    {
        // Required — optimistic-concurrency token, echo back what GET returned.
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();
    }

    public class StaffAttendanceResponseDto
    {
        public Guid Id { get; set; }
        public Guid StaffProfileId { get; set; }
        public DateOnly AttendanceDate { get; set; }
        public AttendanceStatus Status { get; set; }
        public string? Remarks { get; set; }
        public DateTime CreatedAtUtc { get; set; }
        public DateTime? UpdatedAtUtc { get; set; }
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();
    }

    public class StaffProfileCreateDto
    {
        public Guid UserId { get; set; }
        public Guid? BusOperatorId { get; set; }
        public string EmployeeCode { get; set; } = string.Empty;
        public StaffRole Role { get; set; }
        public string? NationalIdNumber { get; set; }
        public DateOnly? JoiningDate { get; set; }
        public string? Address { get; set; }
        public int TotalTripsCompleted { get; set; }
        public bool IsActive { get; set; } = true;
    }

    public class StaffProfileUpdateDto : StaffProfileCreateDto
    {
        // Required — optimistic-concurrency token, echo back what GET returned.
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();
    }

    public class StaffProfileResponseDto
    {
        public Guid Id { get; set; }
        public Guid UserId { get; set; }
        public Guid? BusOperatorId { get; set; }
        public string EmployeeCode { get; set; } = string.Empty;
        public StaffRole Role { get; set; }
        public string? NationalIdNumber { get; set; }
        public DateOnly? JoiningDate { get; set; }
        public string? Address { get; set; }
        public int TotalTripsCompleted { get; set; }
        public bool IsActive { get; set; } = true;
        public DateTime CreatedAtUtc { get; set; }
        public DateTime? UpdatedAtUtc { get; set; }
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();
    }

    public class StaffSalaryCreateDto
    {
        public Guid StaffProfileId { get; set; }
        public DateOnly PayPeriodStart { get; set; }
        public DateOnly PayPeriodEnd { get; set; }
        public decimal Amount { get; set; }
        public bool IsPaid { get; set; }
        public DateTime? PaidAtUtc { get; set; }
        public string? PaymentReference { get; set; }
    }

    public class StaffSalaryUpdateDto : StaffSalaryCreateDto
    {
        // Required — optimistic-concurrency token, echo back what GET returned.
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();
    }

    public class StaffSalaryResponseDto
    {
        public Guid Id { get; set; }
        public Guid StaffProfileId { get; set; }
        public DateOnly PayPeriodStart { get; set; }
        public DateOnly PayPeriodEnd { get; set; }
        public decimal Amount { get; set; }
        public bool IsPaid { get; set; }
        public DateTime? PaidAtUtc { get; set; }
        public string? PaymentReference { get; set; }
        public DateTime CreatedAtUtc { get; set; }
        public DateTime? UpdatedAtUtc { get; set; }
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();
    }

}